(() => {
  "use strict";

  const songs = [
    {
      id: "abba-dancing-queen",
      title: "Dancing Queen",
      artist: "ABBA",
      year: 1976,
      spotifyUri: "spotify:track:0GjEhVFGZW8afUYGChu3Rr",
      spotifyUrl: "https://open.spotify.com/track/0GjEhVFGZW8afUYGChu3Rr",
      tags: ["70s", "pop", "party"],
    },
    {
      id: "queen-bohemian-rhapsody",
      title: "Bohemian Rhapsody",
      artist: "Queen",
      year: 1975,
      spotifyUri: "spotify:track:7tFiyTwD0nx5a1eklYtX2J",
      spotifyUrl: "https://open.spotify.com/track/7tFiyTwD0nx5a1eklYtX2J",
      tags: ["70s", "rock"],
    },
    {
      id: "michael-jackson-billie-jean",
      title: "Billie Jean",
      artist: "Michael Jackson",
      year: 1982,
      spotifyUri: "spotify:track:5ChkMS8OtdzJeqyybCc9R5",
      spotifyUrl: "https://open.spotify.com/track/5ChkMS8OtdzJeqyybCc9R5",
      tags: ["80s", "pop"],
    },
    {
      id: "toto-africa",
      title: "Africa",
      artist: "TOTO",
      year: 1982,
      spotifyUri: "spotify:track:2374M0fQpWi3dLnB54qaLX",
      spotifyUrl: "https://open.spotify.com/track/2374M0fQpWi3dLnB54qaLX",
      tags: ["80s", "rock", "party"],
    },
    {
      id: "a-ha-take-on-me",
      title: "Take On Me",
      artist: "a-ha",
      year: 1985,
      spotifyUri: "spotify:track:2WfaOiMkCvy7F5fcp2zZ8L",
      spotifyUrl: "https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L",
      tags: ["80s", "pop"],
    },
    {
      id: "whitney-i-wanna-dance",
      title: "I Wanna Dance with Somebody",
      artist: "Whitney Houston",
      year: 1987,
      spotifyUri: "spotify:track:2tUBqZG2AbRi7Q0BIrVrEj",
      spotifyUrl: "https://open.spotify.com/track/2tUBqZG2AbRi7Q0BIrVrEj",
      tags: ["80s", "pop", "party"],
    },
    {
      id: "nirvana-smells-like-teen-spirit",
      title: "Smells Like Teen Spirit",
      artist: "Nirvana",
      year: 1991,
      spotifyUri: "spotify:track:5ghIJDpPoe3CfHMGu71E6T",
      spotifyUrl: "https://open.spotify.com/track/5ghIJDpPoe3CfHMGu71E6T",
      tags: ["90s", "rock"],
    },
    {
      id: "oasis-wonderwall",
      title: "Wonderwall",
      artist: "Oasis",
      year: 1995,
      spotifyUri: "spotify:track:5qqabIl2vWzo9ApSC317sa",
      spotifyUrl: "https://open.spotify.com/track/5qqabIl2vWzo9ApSC317sa",
      tags: ["90s", "rock"],
    },
    {
      id: "backstreet-boys-i-want-it-that-way",
      title: "I Want It That Way",
      artist: "Backstreet Boys",
      year: 1999,
      spotifyUri: "spotify:track:6e40mgJiCid5HRAGrbpGA6",
      spotifyUrl: "https://open.spotify.com/track/6e40mgJiCid5HRAGrbpGA6",
      tags: ["90s", "pop", "party"],
    },
    {
      id: "britney-spears-toxic",
      title: "Toxic",
      artist: "Britney Spears",
      year: 2003,
      spotifyUri: "spotify:track:6I9VzXrHxO9rA9A5euc8Ak",
      spotifyUrl: "https://open.spotify.com/track/6I9VzXrHxO9rA9A5euc8Ak",
      tags: ["00s", "pop"],
    },
    {
      id: "outkast-hey-ya",
      title: "Hey Ya!",
      artist: "Outkast",
      year: 2003,
      spotifyUri: "spotify:track:2PpruBYCo4H7WOBJ7Q2EwM",
      spotifyUrl: "https://open.spotify.com/track/2PpruBYCo4H7WOBJ7Q2EwM",
      tags: ["00s", "party"],
    },
    {
      id: "the-killers-mr-brightside",
      title: "Mr. Brightside",
      artist: "The Killers",
      year: 2003,
      spotifyUri: "spotify:track:003vvx7Niy0yvhvHt4a68B",
      spotifyUrl: "https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B",
      tags: ["00s", "rock", "party"],
    },
    {
      id: "shakira-hips-dont-lie",
      title: "Hips Don't Lie",
      artist: "Shakira",
      year: 2005,
      spotifyUri: "spotify:track:3ZFTkvIE7kyPt6Nu3PEa7V",
      spotifyUrl: "https://open.spotify.com/track/3ZFTkvIE7kyPt6Nu3PEa7V",
      tags: ["00s", "pop", "party"],
    },
    {
      id: "gnarls-barkley-crazy",
      title: "Crazy",
      artist: "Gnarls Barkley",
      year: 2006,
      spotifyUri: "spotify:track:1vxw6aYJls2oq3gW0DujAo",
      spotifyUrl: "https://open.spotify.com/track/1vxw6aYJls2oq3gW0DujAo",
      tags: ["00s", "soul", "pop"],
    },
    {
      id: "beyonce-single-ladies",
      title: "Single Ladies",
      artist: "Beyonce",
      year: 2008,
      spotifyUri: "spotify:track:5R9a4t5t5O0IsznsrKPVro",
      spotifyUrl: "https://open.spotify.com/track/5R9a4t5t5O0IsznsrKPVro",
      tags: ["00s", "pop", "party"],
    },
    {
      id: "lady-gaga-bad-romance",
      title: "Bad Romance",
      artist: "Lady Gaga",
      year: 2009,
      spotifyUri: "spotify:track:0SiywuOBRcynK0uKGWdCnn",
      spotifyUrl: "https://open.spotify.com/track/0SiywuOBRcynK0uKGWdCnn",
      tags: ["00s", "pop"],
    },
    {
      id: "adele-rolling-in-the-deep",
      title: "Rolling in the Deep",
      artist: "Adele",
      year: 2010,
      spotifyUri: "spotify:track:1c8gk2PeTE04A1pIDH9YMk",
      spotifyUrl: "https://open.spotify.com/track/1c8gk2PeTE04A1pIDH9YMk",
      tags: ["10s", "pop"],
    },
    {
      id: "daft-punk-get-lucky",
      title: "Get Lucky",
      artist: "Daft Punk feat. Pharrell Williams",
      year: 2013,
      spotifyUri: "spotify:track:2Foc5Q5nqNiosCNqttzHof",
      spotifyUrl: "https://open.spotify.com/track/2Foc5Q5nqNiosCNqttzHof",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "avicii-wake-me-up",
      title: "Wake Me Up",
      artist: "Avicii",
      year: 2013,
      spotifyUri: "spotify:track:0nrRP2bk19rLc0orkWPQk2",
      spotifyUrl: "https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "pharrell-happy",
      title: "Happy",
      artist: "Pharrell Williams",
      year: 2013,
      spotifyUri: "spotify:track:60nZcImufyMA1MKQY3dcCH",
      spotifyUrl: "https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "mark-ronson-uptown-funk",
      title: "Uptown Funk",
      artist: "Mark Ronson feat. Bruno Mars",
      year: 2014,
      spotifyUri: "spotify:track:32OlwWuMpZ6b0aN2RZOeMS",
      spotifyUrl: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS",
      tags: ["10s", "funk", "party"],
    },
    {
      id: "taylor-swift-shake-it-off",
      title: "Shake It Off",
      artist: "Taylor Swift",
      year: 2014,
      spotifyUri: "spotify:track:0cqRj7pUJDkTCEsJkx8snD",
      spotifyUrl: "https://open.spotify.com/track/0cqRj7pUJDkTCEsJkx8snD",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "justin-bieber-sorry",
      title: "Sorry",
      artist: "Justin Bieber",
      year: 2015,
      spotifyUri: "spotify:track:09CtPGIpYB4BrO8qb1RGsF",
      spotifyUrl: "https://open.spotify.com/track/09CtPGIpYB4BrO8qb1RGsF",
      tags: ["10s", "pop"],
    },
    {
      id: "ed-sheeran-shape-of-you",
      title: "Shape of You",
      artist: "Ed Sheeran",
      year: 2017,
      spotifyUri: "spotify:track:7qiZfU4dY1lWllzX7mPBI3",
      spotifyUrl: "https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3",
      tags: ["10s", "pop"],
    },
    {
      id: "billie-eilish-bad-guy",
      title: "bad guy",
      artist: "Billie Eilish",
      year: 2019,
      spotifyUri: "spotify:track:2Fxmhks0bxGSBdJ92vM42m",
      spotifyUrl: "https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m",
      tags: ["10s", "pop"],
    },
    {
      id: "the-weeknd-blinding-lights",
      title: "Blinding Lights",
      artist: "The Weeknd",
      year: 2019,
      spotifyUri: "spotify:track:0VjIjW4GlUZAMYd2vXMi3b",
      spotifyUrl: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "dua-lipa-dont-start-now",
      title: "Don't Start Now",
      artist: "Dua Lipa",
      year: 2019,
      spotifyUri: "spotify:track:6WrI0LAC5M1Rw2MnX2ZvEg",
      spotifyUrl: "https://open.spotify.com/track/6WrI0LAC5M1Rw2MnX2ZvEg",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "the-weeknd-save-your-tears",
      title: "Save Your Tears",
      artist: "The Weeknd",
      year: 2020,
      spotifyUri: "spotify:track:5QO79kh1waicV47BqGRL3g",
      spotifyUrl: "https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g",
      tags: ["20s", "pop"],
    },
    {
      id: "harry-styles-as-it-was",
      title: "As It Was",
      artist: "Harry Styles",
      year: 2022,
      spotifyUri: "spotify:track:4LRPiXqCikLlN15c3yImP7",
      spotifyUrl: "https://open.spotify.com/track/4LRPiXqCikLlN15c3yImP7",
      tags: ["20s", "pop"],
    },
    {
      id: "miley-cyrus-flowers",
      title: "Flowers",
      artist: "Miley Cyrus",
      year: 2023,
      spotifyUri: "spotify:track:0yLdNVWF3Srea0uzk55zFn",
      spotifyUrl: "https://open.spotify.com/track/0yLdNVWF3Srea0uzk55zFn",
      tags: ["20s", "pop"],
    },
  ];

  const extraSongs = [
    ["Kvinde Min", "Gasolin'", 1975, ["da", "rock"]],
    ["Rabalderstræde", "Gasolin'", 1975, ["da", "rock"]],
    ["Langebro", "Gasolin'", 1971, ["da", "rock"]],
    ["Hva' Gør Vi Nu, Lille Du?", "Gasolin'", 1976, ["da", "rock"]],
    ["Midt Om Natten", "Kim Larsen", 1983, ["da", "party"]],
    ["Papirsklip", "Kim Larsen", 1983, ["da", "pop"]],
    ["This Is My Life", "Kim Larsen", 1977, ["da", "pop"]],
    ["Jutlandia", "Kim Larsen & Bellami", 1986, ["da", "rock"]],
    ["Joanna", "Kim Larsen", 1973, ["da", "pop"]],
    ["Hvalen Hvalborg", "Shu-bi-dua", 1976, ["da", "party"]],
    ["Fed Rock", "Shu-bi-dua", 1978, ["da", "rock"]],
    ["Danmark", "Shu-bi-dua", 1978, ["da", "pop"]],
    ["Vuffeli-vov", "Shu-bi-dua", 1980, ["da", "party"]],
    ["De Første Kærester På Månen", "TV-2", 1988, ["da", "pop"]],
    ["Popmusikerens Vise", "TV-2", 1985, ["da", "pop"]],
    ["Kom Lad Os Brokke Os", "TV-2", 1981, ["da", "rock"]],
    ["Alt Hvad Hun Ville Var At Danse", "TV-2", 1988, ["da", "party"]],
    ["Bag Duggede Ruder", "Gnags", 1984, ["da", "rock"]],
    ["Vilde Kaniner", "Gnags", 1984, ["da", "party"]],
    ["Mr. Swing King", "Gnags", 1989, ["da", "party"]],
    ["Når Jeg Bliver Gammel", "Gnags", 1989, ["da", "pop"]],
    ["Vågner I Natten", "Dodo & The Dodos", 1987, ["da", "pop"]],
    ["Sømand Af Verden", "Dodo & The Dodos", 1986, ["da", "pop"]],
    ["Lev Livet Nu", "Dodo & The Dodos", 1989, ["da", "party"]],
    ["Elsk Mig I Nat", "Rocazino", 1985, ["da", "party"]],
    ["All My Love", "Rocazino", 1982, ["da", "pop"]],
    ["Kom Tilbage Nu", "Danseorkestret", 1985, ["da", "party"]],
    ["Regndans", "Danseorkestret", 1986, ["da", "pop"]],
    ["Det Er Mig Der Står Herude Og Banker På", "Thomas Helmig", 1988, ["da", "pop"]],
    ["Stupid Man", "Thomas Helmig", 1994, ["da", "pop"]],
    ["Malaga", "Thomas Helmig", 1986, ["da", "pop"]],
    ["Midnat I Europa", "Thomas Helmig", 1989, ["da", "pop"]],
    ["Tæt På Ækvator", "Lis Sørensen", 1983, ["da", "pop"]],
    ["Mine Øjne De Skal Se", "Lis Sørensen", 1989, ["da", "pop"]],
    ["Fuld Af Nattens Stjerner", "Lis Sørensen", 1993, ["da", "pop"]],
    ["Tusind Stykker", "Anne Linnet", 1988, ["da", "pop"]],
    ["Barndommens Gade", "Anne Linnet", 1986, ["da", "pop"]],
    ["Smuk Og Dejlig", "Shit & Chanel", 1975, ["da", "pop"]],
    ["Den Jeg Elsker", "Sanne Salomonsen", 1988, ["da", "pop"]],
    ["Kærligheden Kalder", "Sanne Salomonsen", 1989, ["da", "pop"]],
    ["Elsker Dig For Evigt", "Lars H.U.G.", 1987, ["da", "pop"]],
    ["Copenhagen Dreaming", "Love Shop", 1997, ["da", "rock"]],
    ["Movie Klip", "Nephew", 2004, ["da", "rock"]],
    ["Igen & Igen &", "Nephew", 2006, ["da", "rock"]],
    ["Hospital", "Nephew", 2004, ["da", "rock"]],
    ["Lækker", "Nik & Jay", 2003, ["da", "party"]],
    ["Hot!", "Nik & Jay", 2002, ["da", "party"]],
    ["Boing!", "Nik & Jay", 2004, ["da", "party"]],
    ["Mod Solnedgangen", "Nik & Jay", 2011, ["da", "pop"]],
    ["Engel", "Rasmus Seebach", 2009, ["da", "pop"]],
    ["Natteravn", "Rasmus Seebach", 2010, ["da", "pop"]],
    ["Olivia", "Rasmus Seebach", 2010, ["da", "pop"]],
    ["Millionær", "Rasmus Seebach feat. Ankerstjerne", 2010, ["da", "pop"]],
    ["Kun For Mig", "Medina", 2008, ["da", "dance"]],
    ["Vi To", "Medina", 2009, ["da", "pop"]],
    ["For Altid", "Medina", 2011, ["da", "dance"]],
    ["Fascination", "Alphabeat", 2007, ["da", "party"]],
    ["10.000 Nights", "Alphabeat", 2007, ["da", "party"]],
    ["From Paris To Berlin", "Infernal", 2004, ["da", "dance"]],
    ["Barbie Girl", "Aqua", 1997, ["da", "party"]],
    ["Imagine", "John Lennon", 1971, ["international", "pop"]],
    ["Stayin' Alive", "Bee Gees", 1977, ["international", "party"]],
    ["September", "Earth, Wind & Fire", 1978, ["international", "party"]],
    ["Hotel California", "Eagles", 1976, ["international", "rock"]],
    ["Don't Stop Me Now", "Queen", 1978, ["international", "rock"]],
    ["Another One Bites The Dust", "Queen", 1980, ["international", "rock"]],
    ["Superstition", "Stevie Wonder", 1972, ["international", "funk"]],
    ["Sweet Home Alabama", "Lynyrd Skynyrd", 1974, ["international", "rock"]],
    ["Go Your Own Way", "Fleetwood Mac", 1977, ["international", "rock"]],
    ["Dreams", "Fleetwood Mac", 1977, ["international", "rock"]],
    ["Born To Run", "Bruce Springsteen", 1975, ["international", "rock"]],
    ["Dancing In The Dark", "Bruce Springsteen", 1984, ["international", "rock"]],
    ["Livin' On A Prayer", "Bon Jovi", 1986, ["international", "rock", "party"]],
    ["Sweet Child O' Mine", "Guns N' Roses", 1987, ["international", "rock"]],
    ["Every Breath You Take", "The Police", 1983, ["international", "pop"]],
    ["Don't You (Forget About Me)", "Simple Minds", 1985, ["international", "pop"]],
    ["Girls Just Want To Have Fun", "Cyndi Lauper", 1983, ["international", "party"]],
    ["Like A Virgin", "Madonna", 1984, ["international", "pop"]],
    ["Like A Prayer", "Madonna", 1989, ["international", "pop"]],
    ["Purple Rain", "Prince", 1984, ["international", "pop"]],
    ["When Doves Cry", "Prince", 1984, ["international", "pop"]],
    ["Never Gonna Give You Up", "Rick Astley", 1987, ["international", "party"]],
    ["Faith", "George Michael", 1987, ["international", "pop"]],
    ["Careless Whisper", "George Michael", 1984, ["international", "pop"]],
    ["Wake Me Up Before You Go-Go", "Wham!", 1984, ["international", "party"]],
    ["Sweet Dreams", "Eurythmics", 1983, ["international", "pop"]],
    ["Here I Go Again", "Whitesnake", 1987, ["international", "rock"]],
    ["The Final Countdown", "Europe", 1986, ["international", "rock"]],
    ["Eye Of The Tiger", "Survivor", 1982, ["international", "rock"]],
    ["Total Eclipse Of The Heart", "Bonnie Tyler", 1983, ["international", "pop"]],
    ["Losing My Religion", "R.E.M.", 1991, ["international", "rock"]],
    ["Zombie", "The Cranberries", 1994, ["international", "rock"]],
    ["Creep", "Radiohead", 1992, ["international", "rock"]],
    ["No Rain", "Blind Melon", 1992, ["international", "rock"]],
    ["Basket Case", "Green Day", 1994, ["international", "rock"]],
    ["Song 2", "Blur", 1997, ["international", "rock"]],
    ["Bitter Sweet Symphony", "The Verve", 1997, ["international", "rock"]],
    ["Torn", "Natalie Imbruglia", 1997, ["international", "pop"]],
    ["...Baby One More Time", "Britney Spears", 1998, ["international", "pop"]],
    ["Wannabe", "Spice Girls", 1996, ["international", "party"]],
    ["Mambo No. 5", "Lou Bega", 1999, ["international", "party"]],
    ["Smooth", "Santana feat. Rob Thomas", 1999, ["international", "pop"]],
    ["Believe", "Cher", 1998, ["international", "dance"]],
    ["All Star", "Smash Mouth", 1999, ["international", "party"]],
    ["Blue (Da Ba Dee)", "Eiffel 65", 1998, ["international", "dance"]],
    ["Around The World", "Daft Punk", 1997, ["international", "dance"]],
    ["One More Time", "Daft Punk", 2000, ["international", "dance"]],
    ["Seven Nation Army", "The White Stripes", 2003, ["international", "rock"]],
    ["In The End", "Linkin Park", 2000, ["international", "rock"]],
    ["Numb", "Linkin Park", 2003, ["international", "rock"]],
    ["Complicated", "Avril Lavigne", 2002, ["international", "pop"]],
    ["Sk8er Boi", "Avril Lavigne", 2002, ["international", "rock"]],
    ["Crazy In Love", "Beyoncé feat. Jay-Z", 2003, ["international", "party"]],
    ["Umbrella", "Rihanna feat. Jay-Z", 2007, ["international", "pop"]],
    ["Don't Stop The Music", "Rihanna", 2007, ["international", "dance"]],
    ["Poker Face", "Lady Gaga", 2008, ["international", "pop"]],
    ["Just Dance", "Lady Gaga", 2008, ["international", "dance"]],
    ["I Gotta Feeling", "The Black Eyed Peas", 2009, ["international", "party"]],
    ["Where Is The Love?", "The Black Eyed Peas", 2003, ["international", "pop"]],
    ["Feel Good Inc.", "Gorillaz", 2005, ["international", "pop"]],
    ["Firework", "Katy Perry", 2010, ["international", "pop"]],
    ["Teenage Dream", "Katy Perry", 2010, ["international", "pop"]],
    ["Call Me Maybe", "Carly Rae Jepsen", 2011, ["international", "party"]],
    ["Somebody That I Used To Know", "Gotye feat. Kimbra", 2011, ["international", "pop"]],
    ["We Found Love", "Rihanna feat. Calvin Harris", 2011, ["international", "dance"]],
    ["Can't Hold Us", "Macklemore & Ryan Lewis", 2011, ["international", "party"]],
    ["Thrift Shop", "Macklemore & Ryan Lewis", 2012, ["international", "party"]],
    ["Radioactive", "Imagine Dragons", 2012, ["international", "rock"]],
    ["Demons", "Imagine Dragons", 2012, ["international", "pop"]],
    ["Royals", "Lorde", 2013, ["international", "pop"]],
    ["Chandelier", "Sia", 2014, ["international", "pop"]],
    ["Cheap Thrills", "Sia", 2016, ["international", "party"]],
    ["Hello", "Adele", 2015, ["international", "pop"]],
    ["Someone Like You", "Adele", 2011, ["international", "pop"]],
    ["Can't Stop The Feeling!", "Justin Timberlake", 2016, ["international", "party"]],
    ["Despacito", "Luis Fonsi feat. Daddy Yankee", 2017, ["international", "party"]],
    ["Havana", "Camila Cabello feat. Young Thug", 2017, ["international", "pop"]],
    ["Señorita", "Shawn Mendes & Camila Cabello", 2019, ["international", "pop"]],
    ["Old Town Road", "Lil Nas X", 2018, ["international", "party"]],
    ["Dance Monkey", "Tones And I", 2019, ["international", "pop"]],
    ["Watermelon Sugar", "Harry Styles", 2019, ["international", "pop"]],
    ["Levitating", "Dua Lipa", 2020, ["international", "dance"]],
    ["Physical", "Dua Lipa", 2020, ["international", "dance"]],
    ["Bad Habits", "Ed Sheeran", 2021, ["international", "pop"]],
    ["Shivers", "Ed Sheeran", 2021, ["international", "pop"]],
    ["Drivers License", "Olivia Rodrigo", 2021, ["international", "pop"]],
    ["Good 4 U", "Olivia Rodrigo", 2021, ["international", "rock"]],
    ["Heat Waves", "Glass Animals", 2020, ["international", "pop"]],
    ["Anti-Hero", "Taylor Swift", 2022, ["international", "pop"]],
    ["Espresso", "Sabrina Carpenter", 2024, ["international", "pop"]],
  ];

  const additionalSongs = [
    ["Silverflame", "Dizzy Mizz Lizzy", 1994, ["da", "rock"]],
    ["Waterline", "Dizzy Mizz Lizzy", 1994, ["da", "rock"]],
    ["Glory", "Dizzy Mizz Lizzy", 1994, ["da", "rock"]],
    ["Love Is a Loser's Game", "Dizzy Mizz Lizzy", 1994, ["da", "rock"]],
    ["11:07 PM", "Dizzy Mizz Lizzy", 1994, ["da", "rock"]],
    ["Rocket Brothers", "Kashmir", 2003, ["da", "rock"]],
    ["Mom in Love, Daddy in Space", "Kashmir", 1999, ["da", "rock"]],
    ["Surfing the Warm Industry", "Kashmir", 2003, ["da", "rock"]],
    ["The Cynic", "Kashmir", 2005, ["da", "rock"]],
    ["Kalifornia", "Kashmir", 2005, ["da", "rock"]],
    ["Am I Wry? No", "Mew", 2000, ["da", "rock"]],
    ["Comforting Sounds", "Mew", 2003, ["da", "rock"]],
    ["156", "Mew", 2003, ["da", "rock"]],
    ["Special", "Mew", 2005, ["da", "rock"]],
    ["The Zookeeper's Boy", "Mew", 2005, ["da", "rock"]],
    ["The Day After Tomorrow", "Saybia", 2002, ["da", "rock"]],
    ["The Second You Sleep", "Saybia", 2002, ["da", "rock"]],
    ["I Surrender", "Saybia", 2004, ["da", "rock"]],
    ["Brilliant Sky", "Saybia", 2002, ["da", "rock"]],
    ["Transparent & Glasslike", "Carpark North", 2003, ["da", "rock"]],
    ["Human", "Carpark North", 2005, ["da", "rock"]],
    ["Shall We Be Grateful", "Carpark North", 2008, ["da", "rock"]],
    ["Save Me From Myself", "Carpark North", 2005, ["da", "rock"]],
    ["32", "Carpark North feat. Stine Bramsen", 2013, ["da", "rock"]],
    ["That Great Love Sound", "The Raveonettes", 2003, ["da", "rock"]],
    ["Love in a Trashcan", "The Raveonettes", 2005, ["da", "rock"]],
    ["Heartbreak Stroll", "The Raveonettes", 2003, ["da", "rock"]],
    ["Aly, Walk With Me", "The Raveonettes", 2007, ["da", "rock"]],
    ["Move Your Feet", "Junior Senior", 2002, ["da", "party"]],
    ["Rhythm Bandits", "Junior Senior", 2002, ["da", "party"]],
    ["Can I Get Get Get", "Junior Senior", 2005, ["da", "party"]],
    ["Played-A-Live", "Safri Duo", 2000, ["da", "dance"]],
    ["Samb-Adagio", "Safri Duo", 2001, ["da", "dance"]],
    ["Baya Baya", "Safri Duo", 2001, ["da", "dance"]],
    ["Self Control", "Infernal", 2006, ["da", "dance"]],
    ["Ten Miles", "Infernal", 2007, ["da", "dance"]],
    ["I Won't Be Crying", "Infernal", 2007, ["da", "dance"]],
    ["Keen on Disco", "Infernal", 2004, ["da", "dance"]],
    ["Doctor Jones", "Aqua", 1997, ["da", "party"]],
    ["Turn Back Time", "Aqua", 1998, ["da", "pop"]],
    ["My Oh My", "Aqua", 1997, ["da", "party"]],
    ["Around the World", "Aqua", 2000, ["da", "party"]],
    ["Best Friend", "Toy-Box", 1999, ["da", "party"]],
    ["Tarzan & Jane", "Toy-Box", 1998, ["da", "party"]],
    ["Witch Doctor", "Cartoons", 1998, ["da", "party"]],
    ["DooDah!", "Cartoons", 1998, ["da", "party"]],
    ["Saturday Night", "Whigfield", 1993, ["da", "dance"]],
    ["Sexy Eyes", "Whigfield", 1996, ["da", "dance"]],
    ["Sunshine Reggae", "Laid Back", 1982, ["da", "pop"]],
    ["White Horse", "Laid Back", 1983, ["da", "dance"]],
    ["Bakerman", "Laid Back", 1989, ["da", "pop"]],
    ["Give It Up", "Cut 'N' Move", 1993, ["da", "dance"]],
    ["I'm Alive", "Cut 'N' Move", 1995, ["da", "dance"]],
    ["This Is How We Party", "S.O.A.P.", 1998, ["da", "party"]],
    ["Ladidi Ladida", "S.O.A.P.", 1998, ["da", "party"]],
    ["The Actor", "Michael Learns to Rock", 1991, ["da", "pop"]],
    ["Sleeping Child", "Michael Learns to Rock", 1993, ["da", "pop"]],
    ["Someday", "Michael Learns to Rock", 1995, ["da", "pop"]],
    ["That's Why", "Michael Learns to Rock", 1995, ["da", "pop"]],
    ["Sleeping My Day Away", "D-A-D", 1989, ["da", "rock"]],
    ["Laugh 'n' 1/2", "D-A-D", 1991, ["da", "rock"]],
    ["Bad Craziness", "D-A-D", 1991, ["da", "rock"]],
    ["Everything Glows", "D-A-D", 2000, ["da", "rock"]],
    ["Scare Yourself", "D-A-D", 2005, ["da", "rock"]],
    ["Let Your Fingers Do the Walking", "Sort Sol", 1993, ["da", "rock"]],
    ["Siggimund Blue", "Sort Sol", 1991, ["da", "rock"]],
    ["Måske Ku' Vi", "Sebastian", 1976, ["da", "pop"]],
    ["Når Lyset Bryder Frem", "Sebastian", 1972, ["da", "pop"]],
    ["Vårvise", "Sebastian", 1972, ["da", "pop"]],
    ["Sui Sui", "Sneakers", 1982, ["da", "pop"]],
    ["Woodoo", "Sneakers", 1981, ["da", "pop"]],
    ["Magi I Luften", "Halberg Larsen", 1983, ["da", "pop"]],
    ["Jeg Vil La' Lyset Brænde", "Ray Dee Ohh", 1988, ["da", "pop"]],
    ["Efterår", "Ray Dee Ohh", 1989, ["da", "pop"]],
    ["Mandagsstævnemøde", "Ray Dee Ohh", 1989, ["da", "pop"]],
    ["Du Er", "News", 1981, ["da", "pop"]],
    ["Jeg Elsker Dig", "News", 1982, ["da", "pop"]],
    ["Indianer", "Tøsedrengene", 1983, ["da", "pop"]],
    ["Sig Du Ka' Li' Mig", "Tøsedrengene", 1981, ["da", "pop"]],
    ["Ud Under Åben Himmel", "Tøsedrengene", 1982, ["da", "pop"]],
    ["Bruge Og Bruges", "Tøsedrengene", 1983, ["da", "pop"]],
    ["Sarai", "Moonjam", 1987, ["da", "pop"]],
    ["Shaida", "Moonjam", 1988, ["da", "pop"]],
    ["Bag De Blå Bjerge", "Moonjam", 1989, ["da", "pop"]],
    ["Den Bedste Tid", "One Two", 1989, ["da", "pop"]],
    ["Billy Boy", "One Two", 1986, ["da", "pop"]],
    ["Midt I En Drøm", "One Two", 1989, ["da", "pop"]],
    ["Holder Øje Med Dig", "Søs Fenger", 1989, ["da", "pop"]],
    ["Inderst Inde", "Søs Fenger", 1993, ["da", "pop"]],
    ["Mon De Kan Reparere Dig", "Lars H.U.G.", 1987, ["da", "pop"]],
    ["On A Long Lonely Night", "Sko/Torp", 1990, ["da", "pop"]],
    ["Get Ready", "Sko/Torp", 1991, ["da", "pop"]],
    ["Bonsoir Madame", "Big Fat Snake", 1997, ["da", "rock"]],
    ["Female Voice", "Big Fat Snake", 1995, ["da", "rock"]],
    ["No Peace Like In Heaven", "Big Fat Snake", 1994, ["da", "rock"]],
    ["Sådan Nogen Som Os", "Poul Krebs", 1995, ["da", "pop"]],
    ["Morrison, Dylan Og Elvis", "Poul Krebs", 1995, ["da", "pop"]],
    ["Små Sensationer", "Poul Krebs", 1995, ["da", "pop"]],
    ["Lyse Nætter", "Alberte", 1991, ["da", "pop"]],
    ["Tænder På Et Kys", "Alberte", 1991, ["da", "pop"]],
    ["Vimmersvej", "Bamses Venner", 1975, ["da", "party"]],
    ["I En Lille Båd Der Gynger", "Bamses Venner", 1978, ["da", "pop"]],
    ["Hvorfor Går Louise Til Bal", "Bamses Venner", 1979, ["da", "party"]],
    ["Pas På Den Knaldrøde Gummibåd", "Birthe Kjær", 1975, ["da", "party"]],
    ["Vi Maler Byen Rød", "Birthe Kjær", 1989, ["da", "party"]],
    ["Smuk Som Et Stjerneskud", "Brødrene Olsen", 2000, ["da", "pop"]],
    ["En Lille Ring Af Guld", "Kandis", 1995, ["da", "party"]],
    ["Drenge Som Mig", "Johnny Deluxe", 2004, ["da", "pop"]],
    ["Elskovspony", "Johnny Deluxe", 2003, ["da", "pop"]],
    ["En Sang Om Kærlighed", "Tue West", 2003, ["da", "pop"]],
    ["Love Will Keep You Warm", "Swan Lee", 2001, ["da", "pop"]],
    ["Tomorrow Never Dies", "Swan Lee", 2001, ["da", "pop"]],
    ["Right Next To The Right One", "Tim Christensen", 2003, ["da", "pop"]],
    ["Love Is A Matter", "Tim Christensen", 2000, ["da", "pop"]],
    ["Whispering At The Top Of My Lungs", "Tim Christensen", 2003, ["da", "pop"]],
    ["Superior", "Tim Christensen", 2008, ["da", "pop"]],
    ["Nobody's Man", "Tina Dickow", 2004, ["da", "pop"]],
    ["Open Wide", "Tina Dickow", 2004, ["da", "pop"]],
    ["Count To Ten", "Tina Dickow", 2007, ["da", "pop"]],
    ["I Will Love You Monday", "Aura Dione", 2008, ["da", "pop"]],
    ["Geronimo", "Aura Dione", 2011, ["da", "pop"]],
    ["Friends", "Aura Dione", 2012, ["da", "pop"]],
    ["Bridges", "Fallulah", 2010, ["da", "pop"]],
    ["Out Of It", "Fallulah", 2010, ["da", "pop"]],
    ["Give Us A Little Love", "Fallulah", 2010, ["da", "pop"]],
    ["Hey Jude", "The Beatles", 1968, ["international", "pop"]],
    ["Let It Be", "The Beatles", 1970, ["international", "pop"]],
    ["Here Comes The Sun", "The Beatles", 1969, ["international", "pop"]],
    ["Yesterday", "The Beatles", 1965, ["international", "pop"]],
    ["Paint It Black", "The Rolling Stones", 1966, ["international", "rock"]],
    ["(I Can't Get No) Satisfaction", "The Rolling Stones", 1965, ["international", "rock"]],
    ["Gimme Shelter", "The Rolling Stones", 1969, ["international", "rock"]],
    ["Heroes", "David Bowie", 1977, ["international", "rock"]],
    ["Life on Mars?", "David Bowie", 1971, ["international", "rock"]],
    ["Space Oddity", "David Bowie", 1969, ["international", "rock"]],
    ["Rocket Man", "Elton John", 1972, ["international", "pop"]],
    ["Your Song", "Elton John", 1970, ["international", "pop"]],
    ["Tiny Dancer", "Elton John", 1971, ["international", "pop"]],
    ["Piano Man", "Billy Joel", 1973, ["international", "pop"]],
    ["We Are the Champions", "Queen", 1977, ["international", "rock"]],
    ["We Will Rock You", "Queen", 1977, ["international", "rock"]],
    ["Mamma Mia", "ABBA", 1975, ["international", "pop"]],
    ["Gimme! Gimme! Gimme! (A Man After Midnight)", "ABBA", 1979, ["international", "pop"]],
    ["Waterloo", "ABBA", 1974, ["international", "pop"]],
    ["Night Fever", "Bee Gees", 1977, ["international", "party"]],
    ["I Will Survive", "Gloria Gaynor", 1978, ["international", "party"]],
    ["Le Freak", "Chic", 1978, ["international", "party"]],
    ["Hot Stuff", "Donna Summer", 1979, ["international", "party"]],
    ["Heart of Glass", "Blondie", 1979, ["international", "pop"]],
    ["London Calling", "The Clash", 1979, ["international", "rock"]],
    ["Highway to Hell", "AC/DC", 1979, ["international", "rock"]],
    ["Back in Black", "AC/DC", 1980, ["international", "rock"]],
    ["Another Brick in the Wall", "Pink Floyd", 1979, ["international", "rock"]],
    ["Sultans of Swing", "Dire Straits", 1978, ["international", "rock"]],
    ["Money for Nothing", "Dire Straits", 1985, ["international", "rock"]],
    ["With or Without You", "U2", 1987, ["international", "rock"]],
    ["One", "U2", 1991, ["international", "rock"]],
    ["Summer of '69", "Bryan Adams", 1984, ["international", "rock"]],
    ["Time After Time", "Cyndi Lauper", 1983, ["international", "pop"]],
    ["Everybody Wants To Rule The World", "Tears for Fears", 1985, ["international", "pop"]],
    ["Enjoy the Silence", "Depeche Mode", 1990, ["international", "pop"]],
    ["You Give Love A Bad Name", "Bon Jovi", 1986, ["international", "rock"]],
    ["Dream On", "Aerosmith", 1973, ["international", "rock"]],
    ["I Don't Want To Miss A Thing", "Aerosmith", 1998, ["international", "rock"]],
    ["November Rain", "Guns N' Roses", 1991, ["international", "rock"]],
    ["Enter Sandman", "Metallica", 1991, ["international", "rock"]],
    ["Nothing Else Matters", "Metallica", 1991, ["international", "rock"]],
    ["Under the Bridge", "Red Hot Chili Peppers", 1991, ["international", "rock"]],
    ["Californication", "Red Hot Chili Peppers", 1999, ["international", "rock"]],
    ["Alive", "Pearl Jam", 1991, ["international", "rock"]],
    ["Everlong", "Foo Fighters", 1997, ["international", "rock"]],
    ["Don't Look Back in Anger", "Oasis", 1995, ["international", "rock"]],
    ["Karma Police", "Radiohead", 1997, ["international", "rock"]],
    ["Yellow", "Coldplay", 2000, ["international", "pop"]],
    ["Viva La Vida", "Coldplay", 2008, ["international", "pop"]],
    ["Fix You", "Coldplay", 2005, ["international", "pop"]],
    ["Beautiful Day", "U2", 2000, ["international", "rock"]],
    ["Angels", "Robbie Williams", 1997, ["international", "pop"]],
    ["Let Me Entertain You", "Robbie Williams", 1997, ["international", "pop"]],
    ["Freedom! '90", "George Michael", 1990, ["international", "pop"]],
    ["Vogue", "Madonna", 1990, ["international", "pop"]],
    ["Hung Up", "Madonna", 2005, ["international", "dance"]],
    ["If I Could Turn Back Time", "Cher", 1989, ["international", "pop"]],
    ["My Heart Will Go On", "Celine Dion", 1997, ["international", "pop"]],
    ["All I Want for Christmas Is You", "Mariah Carey", 1994, ["international", "pop"]],
    ["Fantasy", "Mariah Carey", 1995, ["international", "pop"]],
    ["No Scrubs", "TLC", 1999, ["international", "pop"]],
    ["Say My Name", "Destiny's Child", 1999, ["international", "pop"]],
    ["Halo", "Beyonce", 2008, ["international", "pop"]],
    ["Fallin'", "Alicia Keys", 2001, ["international", "pop"]],
    ["No One", "Alicia Keys", 2007, ["international", "pop"]],
    ["Lose Yourself", "Eminem", 2002, ["international", "hiphop"]],
    ["Without Me", "Eminem", 2002, ["international", "hiphop"]],
    ["Still D.R.E.", "Dr. Dre feat. Snoop Dogg", 1999, ["international", "hiphop"]],
    ["In Da Club", "50 Cent", 2003, ["international", "hiphop"]],
    ["Empire State of Mind", "Jay-Z feat. Alicia Keys", 2009, ["international", "hiphop"]],
    ["Stronger", "Kanye West", 2007, ["international", "hiphop"]],
    ["Hot in Herre", "Nelly", 2002, ["international", "hiphop"]],
    ["Yeah!", "Usher feat. Lil Jon & Ludacris", 2004, ["international", "party"]],
    ["Cry Me a River", "Justin Timberlake", 2002, ["international", "pop"]],
    ["Mirrors", "Justin Timberlake", 2013, ["international", "pop"]],
    ["Boom Boom Pow", "The Black Eyed Peas", 2009, ["international", "party"]],
    ["Maneater", "Nelly Furtado", 2006, ["international", "pop"]],
    ["Say It Right", "Nelly Furtado", 2006, ["international", "pop"]],
    ["Diamonds", "Rihanna", 2012, ["international", "pop"]],
    ["Only Girl (In the World)", "Rihanna", 2010, ["international", "dance"]],
    ["Work", "Rihanna feat. Drake", 2016, ["international", "pop"]],
    ["Born This Way", "Lady Gaga", 2011, ["international", "pop"]],
    ["Shallow", "Lady Gaga & Bradley Cooper", 2018, ["international", "pop"]],
    ["Roar", "Katy Perry", 2013, ["international", "pop"]],
    ["Dark Horse", "Katy Perry feat. Juicy J", 2013, ["international", "pop"]],
    ["Hot N Cold", "Katy Perry", 2008, ["international", "pop"]],
    ["Just the Way You Are", "Bruno Mars", 2010, ["international", "pop"]],
    ["Locked Out of Heaven", "Bruno Mars", 2012, ["international", "pop"]],
    ["Treasure", "Bruno Mars", 2012, ["international", "pop"]],
    ["24K Magic", "Bruno Mars", 2016, ["international", "party"]],
    ["Set Fire to the Rain", "Adele", 2011, ["international", "pop"]],
    ["Skyfall", "Adele", 2012, ["international", "pop"]],
    ["Easy On Me", "Adele", 2021, ["international", "pop"]],
    ["Thinking Out Loud", "Ed Sheeran", 2014, ["international", "pop"]],
    ["Perfect", "Ed Sheeran", 2017, ["international", "pop"]],
    ["Stay With Me", "Sam Smith", 2014, ["international", "pop"]],
    ["I'm Not The Only One", "Sam Smith", 2014, ["international", "pop"]],
    ["Green Light", "Lorde", 2017, ["international", "pop"]],
    ["Elastic Heart", "Sia", 2013, ["international", "pop"]],
    ["Wrecking Ball", "Miley Cyrus", 2013, ["international", "pop"]],
    ["Party in the U.S.A.", "Miley Cyrus", 2009, ["international", "party"]],
    ["Problem", "Ariana Grande feat. Iggy Azalea", 2014, ["international", "pop"]],
    ["Thank U, Next", "Ariana Grande", 2018, ["international", "pop"]],
    ["7 Rings", "Ariana Grande", 2019, ["international", "pop"]],
    ["Love Story", "Taylor Swift", 2008, ["international", "pop"]],
    ["Blank Space", "Taylor Swift", 2014, ["international", "pop"]],
    ["You Belong With Me", "Taylor Swift", 2008, ["international", "pop"]],
    ["Cruel Summer", "Taylor Swift", 2019, ["international", "pop"]],
    ["Closer", "The Chainsmokers feat. Halsey", 2016, ["international", "dance"]],
    ["Levels", "Avicii", 2011, ["international", "dance"]],
    ["The Nights", "Avicii", 2014, ["international", "dance"]],
    ["Summer", "Calvin Harris", 2014, ["international", "dance"]],
    ["Titanium", "David Guetta feat. Sia", 2011, ["international", "dance"]],
    ["Memories", "David Guetta feat. Kid Cudi", 2009, ["international", "dance"]],
    ["Don't You Worry Child", "Swedish House Mafia", 2012, ["international", "dance"]],
    ["Lean On", "Major Lazer & DJ Snake feat. MØ", 2015, ["international", "dance"]],
    ["Rather Be", "Clean Bandit feat. Jess Glynne", 2014, ["international", "dance"]],
    ["Turn Down for What", "DJ Snake & Lil Jon", 2013, ["international", "party"]],
    ["Hotline Bling", "Drake", 2015, ["international", "hiphop"]],
    ["One Dance", "Drake feat. Wizkid & Kyla", 2016, ["international", "dance"]],
    ["The Hills", "The Weeknd", 2015, ["international", "pop"]],
    ["Can't Feel My Face", "The Weeknd", 2015, ["international", "pop"]],
    ["Therefore I Am", "Billie Eilish", 2020, ["international", "pop"]],
    ["Happier Than Ever", "Billie Eilish", 2021, ["international", "rock"]],
  ];

  // Bredt kendte radio-, fest- og fællessangshits, som sikrer mindst
  // 100 standardsange i hver af spillets seks hovedkategorier.
  const categoryExpansionSongs = [
    ["American Pie", "Don McLean", 1971, ["international", "pop"]],
    ["What's Going On", "Marvin Gaye", 1971, ["international", "soul"]],
    ["Maggie May", "Rod Stewart", 1971, ["international", "rock"]],
    ["Take Me Home, Country Roads", "John Denver", 1971, ["international", "party"]],
    ["Lean on Me", "Bill Withers", 1972, ["international", "soul"]],
    ["Starman", "David Bowie", 1972, ["international", "rock"]],
    ["Crocodile Rock", "Elton John", 1972, ["international", "rock", "party"]],
    ["You're So Vain", "Carly Simon", 1972, ["international", "pop"]],
    ["Stuck in the Middle with You", "Stealers Wheel", 1972, ["international", "rock"]],
    ["Killing Me Softly with His Song", "Roberta Flack", 1973, ["international", "soul"]],
    ["Jolene", "Dolly Parton", 1973, ["international", "party"]],
    ["Goodbye Yellow Brick Road", "Elton John", 1973, ["international", "pop"]],
    ["The Joker", "Steve Miller Band", 1973, ["international", "rock"]],
    ["Hooked on a Feeling", "Blue Swede", 1973, ["international", "party"]],
    ["Kung Fu Fighting", "Carl Douglas", 1974, ["international", "party"]],
    ["Can't Get Enough of Your Love, Babe", "Barry White", 1974, ["international", "soul"]],
    ["You Ain't Seen Nothing Yet", "Bachman-Turner Overdrive", 1974, ["international", "rock"]],
    ["Lady Marmalade", "Labelle", 1974, ["international", "party"]],
    ["When Will I See You Again", "The Three Degrees", 1973, ["international", "soul"]],
    ["December, 1963 (Oh, What a Night)", "The Four Seasons", 1975, ["international", "party"]],
    ["That's the Way (I Like It)", "KC and the Sunshine Band", 1975, ["international", "party"]],
    ["Rhinestone Cowboy", "Glen Campbell", 1975, ["international", "pop"]],
    ["SOS", "ABBA", 1975, ["international", "pop", "party"]],
    ["I'm Not in Love", "10cc", 1975, ["international", "pop"]],
    ["Fame", "David Bowie", 1975, ["international", "rock"]],
    ["Fernando", "ABBA", 1976, ["international", "pop"]],
    ["Play That Funky Music", "Wild Cherry", 1976, ["international", "party"]],
    ["Daddy Cool", "Boney M.", 1976, ["international", "party"]],
    ["More Than a Feeling", "Boston", 1976, ["international", "rock"]],
    ["The Boys Are Back in Town", "Thin Lizzy", 1976, ["international", "rock"]],
    ["Carry on Wayward Son", "Kansas", 1976, ["international", "rock"]],
    ["You Make Me Feel Like Dancing", "Leo Sayer", 1976, ["international", "party"]],
    ["Isn't She Lovely", "Stevie Wonder", 1976, ["international", "soul"]],
    ["Somebody to Love", "Queen", 1976, ["international", "rock"]],
    ["Don't Go Breaking My Heart", "Elton John & Kiki Dee", 1976, ["international", "party"]],
    ["How Deep Is Your Love", "Bee Gees", 1977, ["international", "pop"]],
    ["Love Is in the Air", "John Paul Young", 1977, ["international", "party"]],
    ["I Want You to Want Me", "Cheap Trick", 1977, ["international", "rock"]],
    ["Rockin' All Over the World", "Status Quo", 1977, ["international", "rock", "party"]],
    ["You're in My Heart", "Rod Stewart", 1977, ["international", "pop"]],
    ["Rasputin", "Boney M.", 1978, ["international", "party"]],
    ["Rivers of Babylon", "Boney M.", 1978, ["international", "party"]],
    ["Y.M.C.A.", "Village People", 1978, ["international", "party"]],
    ["Baker Street", "Gerry Rafferty", 1978, ["international", "pop"]],
    ["You're the One That I Want", "John Travolta & Olivia Newton-John", 1978, ["international", "party"]],
    ["Summer Nights", "John Travolta & Olivia Newton-John", 1978, ["international", "party"]],
    ["One Way or Another", "Blondie", 1978, ["international", "rock"]],
    ["We Are Family", "Sister Sledge", 1979, ["international", "party"]],
    ["Video Killed the Radio Star", "The Buggles", 1979, ["international", "pop"]],
    ["Don't Bring Me Down", "Electric Light Orchestra", 1979, ["international", "rock"]],
    ["Message in a Bottle", "The Police", 1979, ["international", "rock"]],
    ["The Logical Song", "Supertramp", 1979, ["international", "rock"]],
    ["I Was Made for Lovin' You", "KISS", 1979, ["international", "rock", "party"]],
    ["Disco Tango", "Tommy Seebach", 1979, ["da", "party"]],

    ["Don't You Want Me", "The Human League", 1981, ["international", "pop", "party"]],
    ["Tainted Love", "Soft Cell", 1981, ["international", "pop"]],
    ["Don't Stop Believin'", "Journey", 1981, ["international", "rock", "party"]],
    ["Down Under", "Men at Work", 1981, ["international", "rock", "party"]],
    ["Beat It", "Michael Jackson", 1982, ["international", "pop", "rock"]],
    ["It's Raining Men", "The Weather Girls", 1982, ["international", "party"]],
    ["Red Red Wine", "UB40", 1983, ["international", "pop"]],
    ["Karma Chameleon", "Culture Club", 1983, ["international", "pop", "party"]],
    ["99 Luftballons", "Nena", 1983, ["international", "pop", "party"]],
    ["Footloose", "Kenny Loggins", 1984, ["international", "party"]],
    ["The Power of Love", "Frankie Goes to Hollywood", 1984, ["international", "pop"]],
    ["Heaven", "Bryan Adams", 1984, ["international", "rock"]],
    ["Holding Out for a Hero", "Bonnie Tyler", 1984, ["international", "pop", "party"]],
    ["The Power of Love", "Huey Lewis and the News", 1985, ["international", "rock"]],
    ["Take My Breath Away", "Berlin", 1986, ["international", "pop"]],
    ["Heaven Is a Place on Earth", "Belinda Carlisle", 1987, ["international", "pop", "party"]],
    ["The Look", "Roxette", 1988, ["international", "pop", "rock"]],
    ["Eternal Flame", "The Bangles", 1988, ["international", "pop"]],

    ["U Can't Touch This", "MC Hammer", 1990, ["international", "hiphop", "party"]],
    ["Ice Ice Baby", "Vanilla Ice", 1990, ["international", "hiphop", "party"]],
    ["Black or White", "Michael Jackson", 1991, ["international", "pop", "rock"]],
    ["(Everything I Do) I Do It for You", "Bryan Adams", 1991, ["international", "pop"]],
    ["Rhythm Is a Dancer", "SNAP!", 1992, ["international", "dance", "party"]],
    ["I Will Always Love You", "Whitney Houston", 1992, ["international", "pop"]],
    ["What Is Love", "Haddaway", 1993, ["international", "dance", "party"]],
    ["Mr. Vain", "Culture Beat", 1993, ["international", "dance", "party"]],
    ["The Rhythm of the Night", "Corona", 1993, ["international", "dance", "party"]],
    ["Cotton Eye Joe", "Rednex", 1994, ["international", "party"]],
    ["Scatman (Ski-Ba-Bop-Ba-Dop-Bop)", "Scatman John", 1994, ["international", "dance", "party"]],
    ["Gangsta's Paradise", "Coolio feat. L.V.", 1995, ["international", "hiphop"]],
    ["Everybody (Backstreet's Back)", "Backstreet Boys", 1997, ["international", "pop", "party"]],
    ["Ironic", "Alanis Morissette", 1995, ["international", "pop", "rock"]],
    ["Be My Lover", "La Bouche", 1995, ["international", "dance", "party"]],
    ["Freed from Desire", "Gala", 1996, ["international", "dance", "party"]],
    ["Killing Me Softly", "Fugees", 1996, ["international", "hiphop", "pop"]],
    ["Tubthumping", "Chumbawamba", 1997, ["international", "rock", "party"]],
    ["MMMBop", "Hanson", 1997, ["international", "pop", "party"]],
    ["Kiss Me", "Sixpence None the Richer", 1997, ["international", "pop"]],
    ["Iris", "Goo Goo Dolls", 1998, ["international", "rock"]],
    ["Genie in a Bottle", "Christina Aguilera", 1999, ["international", "pop"]],

    ["Moves Like Jagger", "Maroon 5 feat. Christina Aguilera", 2011, ["international", "pop", "party"]],
    ["What Makes You Beautiful", "One Direction", 2011, ["international", "pop", "party"]],
    ["Party Rock Anthem", "LMFAO feat. Lauren Bennett & GoonRock", 2011, ["international", "dance", "party"]],
    ["Gangnam Style", "PSY", 2012, ["international", "dance", "party"]],
    ["Counting Stars", "OneRepublic", 2013, ["international", "pop"]],
    ["Story of My Life", "One Direction", 2013, ["international", "pop"]],
    ["Rude", "MAGIC!", 2013, ["international", "pop"]],
    ["All About That Bass", "Meghan Trainor", 2014, ["international", "pop", "party"]],
    ["Stressed Out", "Twenty One Pilots", 2015, ["international", "pop"]],
    ["Faded", "Alan Walker", 2015, ["international", "dance"]],
    ["7 Years", "Lukas Graham", 2015, ["da", "pop"]],
    ["Final Song", "MØ", 2016, ["da", "pop"]],
    ["This Is What You Came For", "Calvin Harris feat. Rihanna", 2016, ["international", "dance", "party"]],
    ["Rockabye", "Clean Bandit feat. Sean Paul & Anne-Marie", 2016, ["international", "dance", "party"]],
    ["Castle on the Hill", "Ed Sheeran", 2017, ["international", "pop"]],
    ["Something Just Like This", "The Chainsmokers & Coldplay", 2017, ["international", "dance", "party"]],
    ["Attention", "Charlie Puth", 2017, ["international", "pop"]],
    ["New Rules", "Dua Lipa", 2017, ["international", "pop"]],
    ["Believer", "Imagine Dragons", 2017, ["international", "rock"]],
    ["High Hopes", "Panic! at the Disco", 2018, ["international", "rock", "party"]],
    ["Shotgun", "George Ezra", 2018, ["international", "pop", "party"]],
    ["Someone You Loved", "Lewis Capaldi", 2018, ["international", "pop"]],
    ["Love Someone", "Lukas Graham", 2018, ["da", "pop"]],
    ["Sucker", "Jonas Brothers", 2019, ["international", "pop", "party"]],
    ["Memories", "Maroon 5", 2019, ["international", "pop"]],
    ["I Don't Care", "Ed Sheeran & Justin Bieber", 2019, ["international", "pop"]],
  ];

  // First-release recording metadata: data/sangquiz-expansion-sources.json
  const originExpansionSongs = [
    ["I've Got to Find the Loser","Gasolin'",1970,["da","rock"]],
    ["Blaffersangen","Kim Larsen",1973,["da"]],
    ["Det kimer nu til julefest","Shu-bi-dua",1973,["da","rock"]],
    ["Den gamles drøm","Sebastian",1972,["da"]],
    ["Bryd op rejs ud","Gnags",1973,["da","rock"]],
    ["Advarsel","Anne Linnet",1978,["da"]],
    ["Aha Ha","Bamses Venner",1975,["da"]],
    ["Efter festen","Shit & Chanel",1976,["da"]],
    ["Silky Sally","Gasolin'",1970,["da","rock"]],
    ["Byens hotel","Kim Larsen",1973,["da"]],
    ["Laila","Shu-bi-dua",1973,["da","rock"]],
    ["Den store flugt","Sebastian",1972,["da"]],
    ["Der er så meget","Gnags",1973,["da","rock"]],
    ["Den niende måned","Anne Linnet",1978,["da"]],
    ["Bamsefar","Bamses Venner",1975,["da"]],
    ["Fra dag til dag","Gasolin'",1971,["da","rock"]],
    ["Christianshavns Kanal","Kim Larsen",1973,["da"]],
    ["Rap jul","Shu-bi-dua",1973,["da","rock"]],
    ["Hvis du tror du er noget","Sebastian",1972,["da"]],
    ["Du er dig","Gnags",1973,["da","rock"]],
    ["Den nye ejer","Anne Linnet",1978,["da"]],
    ["En Forunderlig Melodi","Bamses Venner",1975,["da"]],
    ["Hej Christoffer","Gasolin'",1971,["da","rock"]],
    ["De fjorten astronauter","Kim Larsen",1973,["da"]],
    ["Stærk tobak","Shu-bi-dua",1973,["da","rock"]],
    ["Hvor går du hen","Sebastian",1972,["da"]],
    ["Farvelfærd","Gnags",1973,["da","rock"]],
    ["Der bor en ung pige","Anne Linnet",1978,["da"]],
    ["Jeg Har Kun Tre Tænder","Bamses Venner",1975,["da"]],
    ["Laphophora Williamsii","Gasolin'",1971,["da","rock"]],
    ["Den rige og den fattige pige","Kim Larsen",1973,["da"]],
    ["Tynd blues","Shu-bi-dua",1973,["da","rock"]],
    ["Lidt for lidt","Sebastian",1972,["da"]],
    ["Go'dag go'dag","Gnags",1973,["da","rock"]],
    ["Du spørger","Anne Linnet",1978,["da"]],
    ["La' Nu Vær' At Ring","Bamses Venner",1975,["da"]],
    ["Lille Henry","Gasolin'",1971,["da","rock"]],
    ["Det er i dag et vejr","Kim Larsen",1973,["da"]],
    ["Brutale løg","Shu-bi-dua",1974,["da","rock"]],
    ["Rose","Sebastian",1972,["da"]],
    ["Jeg bringer håb","Gnags",1973,["da","rock"]],
    ["Episode","Anne Linnet",1978,["da"]],
    ["Lang Tids Ventetid","Bamses Venner",1975,["da"]],
    ["Lilli-Lilli","Gasolin'",1971,["da","rock"]],
    ["Er du jol mon!","Kim Larsen",1973,["da"]],
    ["El Nossa De La Para Puerto","Shu-bi-dua",1974,["da","rock"]],
    ["Status Quo","Sebastian",1972,["da"]],
    ["Kloden rokker","Gnags",1973,["da","rock"]],
    ["Jalousi","Anne Linnet",1978,["da"]],
    ["Lovlig Alvorlig","Bamses Venner",1975,["da"]],
    ["Solfangen","Gasolin'",1971,["da","rock"]],
    ["Guleroden","Kim Larsen",1973,["da"]],
    ["Generatorbouillon","Shu-bi-dua",1974,["da","rock"]],
    ["Verden skreg","Sebastian",1972,["da"]],
    ["Solsangen","Gnags",1973,["da","rock"]],
    ["Min fortid","Anne Linnet",1978,["da"]],
    ["Marylin","Bamses Venner",1975,["da"]],
    ["Strengt fortroligt","Gasolin'",1971,["da","rock"]],
    ["Hubertus","Kim Larsen",1973,["da"]],
    ["Gøj den gamle","Shu-bi-dua",1974,["da","rock"]],
    ["Afgrunden","Sebastian",1973,["da"]],
    ["Alt for meget / alt for tit","Gnags",1974,["da","rock"]],
    ["Når du forlader mig","Anne Linnet",1978,["da"]],
    ["Må Jeg Gå Med Dig Hjem","Bamses Venner",1975,["da"]],
    ["Tremastet beton","Gasolin'",1971,["da","rock"]],
    ["Hvis din far gir dig lov","Kim Larsen",1973,["da"]],
    ["Karbad baby","Shu-bi-dua",1974,["da","rock"]],
    ["Der står en mand ved vejen","Sebastian",1973,["da"]],
    ["Den røde tråd","Gnags",1974,["da","rock"]],
    ["Skolebørnene","Anne Linnet",1978,["da"]],
    ["Når Det Regner Om Dagen","Bamses Venner",1975,["da"]],
    ["Druktur nr. 1234","Gasolin'",1972,["da","rock"]],
    ["Jacob den glade","Kim Larsen",1973,["da"]],
    ["Lulu rocken går","Shu-bi-dua",1974,["da","rock"]],
    ["Forlis","Sebastian",1973,["da"]],
    ["Det er sommer nu","Gnags",1974,["da","rock"]],
    ["Sorg","Anne Linnet",1978,["da"]],
    ["Rend Og Hop","Bamses Venner",1975,["da"]],
    ["Fi-fi-dong","Gasolin'",1972,["da","rock"]],
    ["Maria","Kim Larsen",1973,["da"]],
    ["Midnatsluskeren","Shu-bi-dua",1974,["da","rock"]],
    ["Hey Ho","Sebastian",1973,["da"]],
    ["Det er så svært at forstå","Gnags",1974,["da","rock"]],
    ["Se Min Læge Er Diktator","Bamses Venner",1975,["da"]],
    ["Hvorfor er der aldrig nogen der tør tage en chance","Gasolin'",1972,["da","rock"]],
    ["Nanna","Kim Larsen",1973,["da"]],
    ["Min baby bor i højhus","Shu-bi-dua",1974,["da","rock"]],
    ["In eller out","Sebastian",1973,["da"]],
    ["Helt uden ord","Gnags",1974,["da","rock"]],
    ["Send Mig Et Minde","Bamses Venner",1975,["da"]],
    ["Nanna","Gasolin'",1972,["da","rock"]],
    ["På en gren i vort kvarter","Kim Larsen",1973,["da"]],
    ["Aldrig mere","TV-2",1981,["da","rock"]],
    ["Alene","Gnags",1980,["da","rock"]],
    ["Donnez-Moi Du feu","Kim Larsen",1981,["da"]],
    ["Bedst som vi leger","Anne Linnet",1980,["da"]],
    ["Det er nat nu","Thomas Helmig",1985,["da"]],
    ["Det Blå Hotel","Lis Sørensen",1983,["da"]],
    ["10 Knots","D-A-D",1987,["da","rock"]],
    ["Columbia","Rocazino",1983,["da"]],
    ["Alene","Tøsedrengene",1981,["da"]],
    ["Atmosfære","TV-2",1981,["da","rock"]],
    ["De nye indianere","Gnags",1980,["da","rock"]],
    ["Dreamer","Kim Larsen",1981,["da"]],
    ["City-Fallen Angel","Anne Linnet",1980,["da"]],
    ["Det går over","Thomas Helmig",1985,["da"]],
    ["Du Kom Når Jeg Kaldte","Lis Sørensen",1983,["da"]],
    ["Black Crickets","D-A-D",1987,["da","rock"]],
    ["Jeg savner dig","Rocazino",1983,["da"]],
    ["Den tyske fod","Tøsedrengene",1981,["da"]],
    ["Boligblok A","TV-2",1981,["da","rock"]],
    ["Hotel Harmonien","Gnags",1980,["da","rock"]],
    ["Hunger","Kim Larsen",1981,["da"]],
    ["De voksnes sønda'","Anne Linnet",1980,["da"]],
    ["Du vil videre","Thomas Helmig",1985,["da"]],
    ["Haven't Got Enough","Lis Sørensen",1983,["da"]],
    ["God's Favorite","D-A-D",1987,["da","rock"]],
    ["Kniven","Rocazino",1983,["da"]],
    ["Lamperøg","Tøsedrengene",1981,["da"]],
    ["Er det her vores dans?","TV-2",1981,["da","rock"]],
    ["Johnnyboy","Gnags",1980,["da","rock"]],
    ["Jungle Dreams","Kim Larsen",1981,["da"]],
    ["Dolly's Lounge","Anne Linnet",1980,["da"]],
    ["Et sted derude","Thomas Helmig",1985,["da"]],
    ["Himmelen Ned På Jorden","Lis Sørensen",1983,["da"]],
    ["Mightyhighty High","D-A-D",1987,["da","rock"]],
    ["Lige linealer","Rocazino",1983,["da"]],
    ["Mit livs livret","Tøsedrengene",1981,["da"]],
    ["Fantastiske Toyota","TV-2",1981,["da","rock"]],
    ["Nyt årti","Gnags",1980,["da","rock"]],
    ["Rock'n'Roll City","Kim Larsen",1981,["da"]],
    ["Don't Wait","Anne Linnet",1980,["da"]],
    ["Fed lykke","Thomas Helmig",1985,["da"]],
    ["Indtil Dig Igen","Lis Sørensen",1983,["da"]],
    ["There's a Ship","D-A-D",1987,["da","rock"]],
    ["Med dig","Rocazino",1983,["da"]],
    ["Når du vågner","Tøsedrengene",1981,["da"]],
    ["Hele ugen alene","TV-2",1981,["da","rock"]],
    ["Rytmehans","Gnags",1980,["da","rock"]],
    ["Still Love You","Kim Larsen",1981,["da"]],
    ["Dyresang","Anne Linnet",1980,["da"]],
    ["Lang tid siden","Thomas Helmig",1985,["da"]],
    ["Jalousi","Lis Sørensen",1983,["da"]],
    ["Girl Nation","D-A-D",1989,["da","rock"]],
    ["Paris","Rocazino",1983,["da"]],
    ["Rastamand","Tøsedrengene",1981,["da"]],
    ["Hva ska jeg svare mit TV?","TV-2",1981,["da","rock"]],
    ["Verden er sindsyg","Gnags",1980,["da","rock"]],
    ["…and So Did I","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["Art Of Me","Kashmir",1994,["da","rock"]],
    ["D-Law","D-A-D",1991,["da","rock"]],
    ["21","Love Shop",1990,["da","rock"]],
    ["Alle dine veje","Thomas Helmig",1990,["da"]],
    ["Alt det du brænder for","Poul Krebs",1990,["da"]],
    ["Roses Are Red","Aqua",1996,["da"]],
    ["African Queen","Michael Learns to Rock",1991,["da"]],
    ["67 Seas in Your Eyes","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["Christians Dive","Kashmir",1994,["da","rock"]],
    ["Day of Wrong Moves","D-A-D",1991,["da","rock"]],
    ["Alt jeg ser er hendes ryg","Love Shop",1990,["da","rock"]],
    ["Bimbo i himlen","Thomas Helmig",1990,["da"]],
    ["Brudebuketten","Poul Krebs",1990,["da"]],
    ["Be a Man","Aqua",1997,["da"]],
    ["Come on and Dance","Michael Learns to Rock",1991,["da"]],
    ["Barbedwired Baby's Dream","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["Don't Look Back It's Probably Hypochondriac Jack Having A Heart Attack","Kashmir",1994,["da","rock"]],
    ["Down That Dusty 3'rd World Road","D-A-D",1991,["da","rock"]],
    ["En lørdag aften","Love Shop",1990,["da","rock"]],
    ["Brønde uden vand","Thomas Helmig",1990,["da"]],
    ["En arm hun kunne sove i","Poul Krebs",1990,["da"]],
    ["Calling You","Aqua",1997,["da"]],
    ["Crazy Dream","Michael Learns to Rock",1991,["da"]],
    ["For God's Sake","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["Leather Crane","Kashmir",1994,["da","rock"]],
    ["Makin' Fun Of Money","D-A-D",1991,["da","rock"]],
    ["En Nat Bliver Det Sommer","Love Shop",1990,["da","rock"]],
    ["En gang til","Thomas Helmig",1990,["da"]],
    ["Fri som et forår","Poul Krebs",1990,["da"]],
    ["Didn’t I","Aqua",1997,["da"]],
    ["Gone After Midnight","Michael Learns to Rock",1991,["da"]],
    ["Hidden War","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["Little Old Birdy Funk Thing","Kashmir",1994,["da","rock"]],
    ["Riskin' It All","D-A-D",1991,["da","rock"]],
    ["I den nye by","Love Shop",1990,["da","rock"]],
    ["Giv mig din mund","Thomas Helmig",1990,["da"]],
    ["Hvis du ser min kæreste","Poul Krebs",1990,["da"]],
    ["Good Morning Sunshine","Aqua",1997,["da"]],
    ["I Still Carry On","Michael Learns to Rock",1991,["da"]],
    ["Hurry Hurry","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["Rose","Kashmir",1994,["da","rock"]],
    ["Rock 'n' Rock Radar","D-A-D",1991,["da","rock"]],
    ["Idag så bedre ud igår","Love Shop",1990,["da","rock"]],
    ["Lad mig aldrig miste dig","Thomas Helmig",1990,["da"]],
    ["Hvis vi var sammen hele tiden","Poul Krebs",1990,["da"]],
    ["Happy Boys & Girls","Aqua",1997,["da"]],
    ["My Blue Angel","Michael Learns to Rock",1991,["da"]],
    ["Love Me a Little","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["The Story Of Jamie Fame Flame","Kashmir",1994,["da","rock"]],
    ["Are We Alive Here???","D-A-D",1995,["da","rock"]],
    ["På Viborgvej","Love Shop",1990,["da","rock"]],
    ["Mit livs kærlighed","Thomas Helmig",1990,["da"]],
    ["Jennifer","Poul Krebs",1990,["da"]],
    ["Heat of the Night","Aqua",1997,["da"]],
    ["25 Minutes","Michael Learns to Rock",1993,["da"]],
    ["Mother Nature's Recipe","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["Vicious Passion","Kashmir",1994,["da","rock"]],
    ["Blood In/Out","D-A-D",1995,["da","rock"]],
    ["Tag mig hjem nu","Love Shop",1990,["da","rock"]],
    ["Modvind","Thomas Helmig",1990,["da"]],
    ["Monte Carlo","Poul Krebs",1990,["da"]],
    ["Complicated Heart","Michael Learns to Rock",1993,["da"]],
    ["Too Close to Stab","Dizzy Mizz Lizzy",1994,["da","rock"]],
    ["Yellow","Kashmir",1994,["da","rock"]],
    ["Candid","D-A-D",1995,["da","rock"]],
    ["Til stjernerne","Love Shop",1990,["da","rock"]],
    ["100 Years","Nephew",2000,["da","rock"]],
    ["Just a Phase","Kashmir",2000,["da","rock"]],
    ["Her Voice Is Beyond Her Years","Mew",2000,["da","rock"]],
    ["Come Closer","Saybia",2001,["da","rock"]],
    ["40 Days","Carpark North",2003,["da","rock"]],
    ["Den anden side","Rasmus Seebach",2009,["da"]],
    ["Afklaret","Medina",2007,["da"]],
    ["21st Century High","Tim Christensen",2000,["da","rock"]],
    ["26 Friends","Tina Dickow",2000,["da"]],
    ["Bedtime Now","Nephew",2000,["da","rock"]],
    ["Home Dead","Kashmir",2001,["da","rock"]],
    ["King Christian","Mew",2000,["da","rock"]],
    ["Dressed in Black","Saybia",2001,["da","rock"]],
    ["Homeland","Carpark North",2003,["da","rock"]],
    ["Den jeg er","Rasmus Seebach",2009,["da"]],
    ["Alene","Medina",2007,["da"]],
    ["Caterpillar","Tim Christensen",2000,["da","rock"]],
    ["Different","Tina Dickow",2000,["da"]],
    ["Carlsberg Nights","Nephew",2000,["da","rock"]],
    ["Undisturbed","Kashmir",2001,["da","rock"]],
    ["Mica","Mew",2000,["da","rock"]],
    ["Fool's Corner","Saybia",2001,["da","rock"]],
    ["I & You","Carpark North",2003,["da","rock"]],
    ["En skygge af dig selv","Rasmus Seebach",2009,["da"]],
    ["Du taber mig","Medina",2007,["da"]],
    ["Falling to Pieces","Tim Christensen",2000,["da","rock"]],
    ["Boys and Girls","Tina Dickow",2003,["da"]],
    ["Circulating Slow","Nephew",2000,["da","rock"]],
    ["Big Fresh","Kashmir",2003,["da","rock"]],
    ["Behind the Drapes","Mew",2002,["da","rock"]],
    ["7 Demons","Saybia",2002,["da","rock"]],
    ["In the Dark","Carpark North",2003,["da","rock"]],
    ["Gi' slip","Rasmus Seebach",2009,["da"]],
    ["Find beatet","Medina",2007,["da"]],
    ["Get the Fuck Out of My Mind","Tim Christensen",2000,["da","rock"]],
    ["Do Something","Tina Dickow",2003,["da"]],
    ["Downtown Europe","Nephew",2000,["da","rock"]],
    ["Bodmin Pill","Kashmir",2003,["da","rock"]],
    ["She Spider","Mew",2003,["da","rock"]],
    ["Empty Stairs","Saybia",2002,["da","rock"]],
    ["Kiss Me","Carpark North",2003,["da","rock"]],
    ["Glad igen","Rasmus Seebach",2009,["da"]],
    ["For hvad det er værd","Medina",2007,["da"]],
    ["King’s Garden","Tim Christensen",2000,["da","rock"]],
    ["Let's Get Lost","Tina Dickow",2003,["da"]],
    ["Oyster Hall","Nephew",2000,["da","rock"]],
    ["In the Sand","Kashmir",2003,["da","rock"]],
    ["Snow Brigade","Mew",2003,["da","rock"]],
    ["In Spite Of","Saybia",2002,["da","rock"]],
    ["Spain","Carpark North",2003,["da","rock"]],
    ["Falder","Rasmus Seebach",2011,["da"]],
    ["Apologize","Lukas Graham",2012,["da"]],
    ["Jesus Jesus","Nephew",2010,["da","rock"]],
    ["Beasts","Carpark North",2010,["da","rock"]],
    ["Copenhagen","Tina Dickow",2010,["da"]],
    ["365 Degrees","Alphabeat",2010,["da"]],
    ["Back and Forth","Fallulah",2010,["da"]],
    ["I mine øjne","Rasmus Seebach",2011,["da"]],
    ["Before the Morning Sun","Lukas Graham",2012,["da"]],
    ["Alt er hårdt","Nephew",2012,["da","rock"]],
    ["Just Human","Carpark North",2010,["da","rock"]],
    ["Home","Tina Dickow",2010,["da"]],
    ["Heat Wave","Alphabeat",2010,["da"]],
    ["Hey You","Fallulah",2010,["da"]],
    ["Igen i dag","Rasmus Seebach",2011,["da"]],
    ["Criminal Mind","Lukas Graham",2012,["da"]],
    ["Alt er synd","Nephew",2012,["da","rock"]],
    ["Subusual","Carpark North",2010,["da","rock"]],
    ["Instead","Tina Dickow",2010,["da"]],
    ["Till I Get Round","Alphabeat",2010,["da"]],
    ["Hold Your Horses","Fallulah",2010,["da"]],
    ["Lys i din lejlighed","Rasmus Seebach",2011,["da"]],
    ["Don't Hurt Me This Way","Lukas Graham",2012,["da"]],
    ["De satans hæmninger","Nephew",2012,["da","rock"]],
    ["Transparent","Carpark North",2010,["da","rock"]],
    ["Paper Thin","Tina Dickow",2010,["da"]],
    ["Brand New Day","Alphabeat",2012,["da"]],
    ["I Lay My Head","Fallulah",2010,["da"]],
    ["Mer' end kærlighed","Rasmus Seebach",2011,["da"]],
    ["Drunk In the Morning","Lukas Graham",2012,["da"]],
    ["Fem rum","Nephew",2012,["da","rock"]],
    ["Army of Open Arms","Carpark North",2013,["da","rock"]],
    ["Sacré Coeur","Tina Dickow",2010,["da"]],
    ["Express Non‐Stop","Alphabeat",2012,["da"]],
    ["New York, You're My Concrete Lover","Fallulah",2010,["da"]],
    ["Nangijala","Rasmus Seebach",2011,["da"]],
    ["Moving Alone","Lukas Graham",2012,["da"]],
    ["Gå med dig","Nephew",2012,["da","rock"]],
    ["Better Off Alone","Carpark North",2014,["da","rock"]],
    ["Strong Man","Tina Dickow",2010,["da"]],
    ["Love on the Line","Alphabeat",2012,["da"]],
    ["Only Human","Fallulah",2010,["da"]],
    ["Ringe i vandet","Rasmus Seebach",2011,["da"]],
    ["Never Let Me Down","Lukas Graham",2012,["da"]],
    ["Hjertestarter","Nephew",2012,["da","rock"]],
    ["Brothers","Carpark North",2014,["da","rock"]],
    ["The City / London","Tina Dickow",2010,["da"]],
    ["Love Sea","Alphabeat",2012,["da"]],
    ["The Black Cat Neighbourhood","Fallulah",2010,["da"]],
    ["Sirenerne","Rasmus Seebach",2011,["da"]],
    ["Nice Guy","Lukas Graham",2012,["da"]],
    ["Klokken 25","Nephew",2012,["da","rock"]],
    ["Copenhagen","Carpark North",2014,["da","rock"]],
    ["Watching Him Go","Tina Dickow",2010,["da"]],
    ["Mad About You","Alphabeat",2012,["da"]],
    ["Use It for Good","Fallulah",2010,["da"]],
    ["Under stjernerne på himlen","Rasmus Seebach",2011,["da"]],
    ["Ordinary Things","Lukas Graham",2012,["da"]],
    ["Søndagsbange","Nephew",2012,["da","rock"]],
    ["I Walk On","Carpark North",2014,["da","rock"]],
    ["Kids Go Where the Light Is On","Tina Dickow",2012,["da"]],
    ["Show Me What Love Is","Alphabeat",2012,["da"]],
    ["Wailing","Fallulah",2010,["da"]],
    ["Vi lever","Rasmus Seebach",2011,["da"]],
    ["Red Wine","Lukas Graham",2012,["da"]],
    ["Tak du","Nephew",2012,["da","rock"]],
    ["One to Breathe For","Carpark North",2014,["da","rock"]],
    ["Moon to Let","Tina Dickow",2012,["da"]],
    ["Since I Met You","Alphabeat",2012,["da"]],
    ["Work Song","Fallulah",2010,["da"]],
    ["Vover på at gå","Rasmus Seebach",2011,["da"]],
    ["Happy Home","Lukas Graham",2013,["da"]],
    ["Amsterdam","Nephew",2018,["da","rock"]],
    ["Phoenix","Carpark North",2014,["da","rock"]],
    ["Point of No Return","Tina Dickow",2012,["da"]],
    ["The Beat Don’t Stop","Alphabeat",2012,["da"]],
    ["You Don't Care","Fallulah",2010,["da"]],
    ["De ka' sig' hva' de vil","Rasmus Seebach",2013,["da"]],
    ["Mama Said","Lukas Graham",2014,["da"]],
    ["At Dø Er At Rejse","Nephew",2018,["da","rock"]],
    ["Renegade","Carpark North",2014,["da","rock"]],
    ["Sunrise","Tina Dickow",2012,["da"]],
    ["Vacation","Alphabeat",2012,["da"]],
    ["13th Cigarette","Fallulah",2013,["da"]],
    ["Du' det dejligste","Rasmus Seebach",2013,["da"]],
    ["Don't You Worry 'Bout Me","Lukas Graham",2015,["da"]],
    ["Den Blå Anemone","Nephew",2018,["da","rock"]],
    ["Home of Heartache","Carpark North",2015,["da","rock"]],
    ["The Other Side","Tina Dickow",2012,["da"]],
    ["Younger Than Yesterday","Alphabeat",2012,["da"]],
    ["Car Window","Fallulah",2013,["da"]],
    ["En verden uden dig","Rasmus Seebach",2013,["da"]],
    ["Funeral","Lukas Graham",2015,["da"]],
    ["Dmii","Nephew",2018,["da","rock"]],
    ["We Hold the Stars","Carpark North",2015,["da","rock"]],
    ["The Time of Our Lives","Tina Dickow",2012,["da"]],
    ["Merry‐Go‐Round","ABBA",1972,["international"]],
    ["Great King Rat","Queen",1973,["international","rock"]],
    ["All the Madmen","David Bowie",1970,["international","rock"]],
    ["Earl Gray","Fleetwood Mac",1970,["international","rock"]],
    ["Amoreena","Elton John",1970,["international"]],
    ["Heaven Help us All","Stevie Wonder",1970,["international"]],
    ["Santa Rosa","ABBA",1972,["international"]],
    ["Liar","Queen",1973,["international","rock"]],
    ["Memory of a Free Festival, Part 2","David Bowie",1970,["international","rock"]],
    ["Green Manalishi","Fleetwood Mac",1970,["international","rock"]],
    ["Ballad of a Well‐Known Gun","Elton John",1970,["international"]],
    ["I Gotta Have a Song","Stevie Wonder",1970,["international"]],
    ["Disillusion","ABBA",1973,["international"]],
    ["Modern Times Rock ’n’ Roll","Queen",1973,["international","rock"]],
    ["She Shook Me Cold","David Bowie",1970,["international","rock"]],
    ["Hi Ho Silver","Fleetwood Mac",1970,["international","rock"]],
    ["Border Song","Elton John",1970,["international"]],
    ["Sugar","Stevie Wonder",1970,["international"]],
    ["I Am Just a Girl","ABBA",1973,["international"]],
    ["Son and Daughter","Queen",1973,["international","rock"]],
    ["Kooks","David Bowie",1971,["international","rock"]],
    ["Jewel Eyed Judy","Fleetwood Mac",1970,["international","rock"]],
    ["Come Down in Time","Elton John",1970,["international"]],
    ["Borderline","Madonna",1983,["international"]],
    ["Baby Be Mine","Michael Jackson",1982,["international"]],
    ["Jack U Off","Prince",1981,["international"]],
    ["Greatest Love of All","Whitney Houston",1985,["international"]],
    ["Boys Say Go!","Depeche Mode",1981,["international"]],
    ["An Cat Dubh","U2",1980,["international","rock"]],
    ["Don’t Try Suicide","Queen",1980,["international","rock"]],
    ["Breakout","Bon Jovi",1984,["international","rock"]],
    ["Burning Up","Madonna",1983,["international"]],
    ["Can’t Get Outta the Rain","Michael Jackson",1982,["international"]],
    ["Private Joy","Prince",1981,["international"]],
    ["Saving All My Love for You","Whitney Houston",1985,["international"]],
    ["Nodisco","Depeche Mode",1981,["international"]],
    ["Another Time, Another Place","U2",1980,["international","rock"]],
    ["Flash","Queen",1980,["international","rock"]],
    ["Burning for Love","Bon Jovi",1984,["international","rock"]],
    ["Lucky Star","Madonna",1983,["international"]],
    ["Human Nature","Michael Jackson",1982,["international"]],
    ["Ronnie, Talk to Russia","Prince",1981,["international"]],
    ["Someone for Me","Whitney Houston",1985,["international"]],
    ["Now, This Is Fun","Depeche Mode",1982,["international"]],
    ["Into the Heart","U2",1980,["international","rock"]],
    ["Play the Game","Queen",1980,["international","rock"]],
    ["Runaway","Bon Jovi",1984,["international","rock"]],
    ["Think of Me","Madonna",1983,["international"]],
    ["The Lady in My Life","Michael Jackson",1982,["international"]],
    ["Sexuality","Prince",1981,["international"]],
    ["You Give Good Love","Whitney Houston",1985,["international"]],
    ["Shouldn’t Have Done That","Depeche Mode",1982,["international"]],
    ["Fire","U2",1981,["international","rock"]],
    ["Action This Day","Queen",1982,["international","rock"]],
    ["She Don’t Know Me","Bon Jovi",1984,["international","rock"]],
    ["Material Girl","Madonna",1984,["international"]],
    ["Wanna Be Startin’ Somethin’","Michael Jackson",1982,["international"]],
    ["D.M.S.R.","Prince",1982,["international"]],
    ["Didn't We Almost Have It All","Whitney Houston",1987,["international"]],
    ["And Then…","Depeche Mode",1983,["international"]],
    ["J. Swallow","U2",1981,["international","rock"]],
    ["Cool Cat","Queen",1982,["international","rock"]],
    ["Always Run to You","Bon Jovi",1985,["international","rock"]],
    ["Over and Over","Madonna",1984,["international"]],
    ["Farewell My Summer Love","Michael Jackson",1984,["international"]],
    ["Let’s Pretend We’re Married","Prince",1982,["international"]],
    ["For the Love of You","Whitney Houston",1987,["international"]],
    ["Fools","Depeche Mode",1983,["international"]],
    ["Scarlet","U2",1981,["international","rock"]],
    ["Life Is Real","Queen",1982,["international","rock"]],
    ["Only Lonely","Bon Jovi",1985,["international","rock"]],
    ["Ain't No Big Deal","Madonna",1985,["international"]],
    ["Girl You’re So Together","Michael Jackson",1984,["international"]],
    ["Adore","Prince",1987,["international"]],
    ["Just the Lonely Talking Again","Whitney Houston",1987,["international"]],
    ["More Than a Party","Depeche Mode",1983,["international"]],
    ["Like a Song…","U2",1983,["international","rock"]],
    ["I Go Crazy","Queen",1984,["international","rock"]],
    ["The Hardest Part Is the Night","Bon Jovi",1985,["international","rock"]],
    ["Gambler","Madonna",1985,["international"]],
    ["Bad","Michael Jackson",1987,["international"]],
    ["Forever in My Life","Prince",1987,["international"]],
    ["Love Is a Contact Sport","Whitney Houston",1987,["international"]],
    ["Something in the Way","Nirvana",1991,["international","rock"]],
    ["Cigarettes & Alcohol","Oasis",1994,["international","rock"]],
    ["I Know","Blur",1990,["international","rock"]],
    ["Inside My Head","Radiohead",1992,["international","rock"]],
    ["Best Thing in Town","Green Day",1990,["international","rock"]],
    ["Love Takes Time","Mariah Carey",1990,["international"]],
    ["Bumper to Bumper","Spice Girls",1996,["international"]],
    ["Christmas Time","Backstreet Boys",1996,["international"]],
    ["D’yer Wanna Be a Spaceman","Oasis",1994,["international","rock"]],
    ["Bad Day","Blur",1991,["international","rock"]],
    ["Faithless, the Wonderboy","Radiohead",1993,["international","rock"]],
    ["I Was There","Green Day",1990,["international","rock"]],
    ["Prisoner","Mariah Carey",1990,["international"]],
    ["If U Can't Dance","Spice Girls",1996,["international"]],
    ["Darlin’","Backstreet Boys",1996,["international"]],
    ["Rock ’n’ Roll Star","Oasis",1994,["international","rock"]],
    ["Bang","Blur",1991,["international","rock"]],
    ["Stop Whispering","Radiohead",1993,["international","rock"]],
    ["My Generation","Green Day",1990,["international","rock"]],
    ["Sent From Up Above","Mariah Carey",1990,["international"]],
    ["Love Thing","Spice Girls",1996,["international"]],
    ["Every Time I Close My Eyes","Backstreet Boys",1996,["international"]],
    ["Sad Song","Oasis",1994,["international","rock"]],
    ["High Cool","Blur",1991,["international","rock"]],
    ["Bullet Proof..I Wish I Was","Radiohead",1994,["international","rock"]],
    ["Paper Lanterns","Green Day",1990,["international","rock"]],
    ["Make It Happen","Mariah Carey",1991,["international"]],
    ["Mama","Spice Girls",1996,["international"]],
    ["I Wanna Be With You","Backstreet Boys",1996,["international"]],
    ["It’s Better People","Oasis",1995,["international","rock"]],
    ["I’m All Over","Blur",1991,["international","rock"]],
    ["How Can You Be Sure?","Radiohead",1994,["international","rock"]],
    ["Sweet Children","Green Day",1990,["international","rock"]],
    ["All I’ve Ever Wanted","Mariah Carey",1993,["international"]],
    ["Naked","Spice Girls",1996,["international"]],
    ["Let's Have a Party","Backstreet Boys",1996,["international"]],
    ["Some Might Say","Oasis",1995,["international","rock"]],
    ["Mr. Briggs","Blur",1991,["international","rock"]],
    ["Killer Cars","Radiohead",1994,["international","rock"]],
    ["Dominated Love Slave","Green Day",1991,["international","rock"]],
    ["Dreamlover","Mariah Carey",1993,["international"]],
    ["One of These Girls","Spice Girls",1996,["international"]],
    ["Nobody but You","Backstreet Boys",1996,["international"]],
    ["Step Out","Oasis",1995,["international","rock"]],
    ["Oily Water","Blur",1991,["international","rock"]],
    ["Lozenge of Love","Radiohead",1994,["international","rock"]],
    ["I Want to Be Alone","Green Day",1991,["international","rock"]],
    ["Brothers and Sisters","Coldplay",2000,["international","rock"]],
    ["Smile Like You Mean It","The Killers",2003,["international","rock"]],
    ["Work It Out","Beyoncé",2002,["international"]],
    ["Hypnotized","Rihanna",2005,["international"]],
    ["Stronger","Britney Spears",2000,["international"]],
    ["Butterflyz","Alicia Keys",2001,["international"]],
    ["Cure for the Itch","Linkin Park",2000,["international","rock"]],
    ["Again Again","Lady Gaga",2008,["international"]],
    ["Careful Where You Stand","Coldplay",2000,["international","rock"]],
    ["Who Let You Go","The Killers",2003,["international","rock"]],
    ["Be With You","Beyoncé",2003,["international"]],
    ["Let Me","Rihanna",2005,["international"]],
    ["Walk on By","Britney Spears",2000,["international"]],
    ["Lovin’ U","Alicia Keys",2001,["international"]],
    ["Papercut","Linkin Park",2000,["international","rock"]],
    ["Beautiful, Dirty, Rich","Lady Gaga",2008,["international"]],
    ["Don’t Panic","Coldplay",2000,["international","rock"]],
    ["Everything Will Be Alright","The Killers",2004,["international","rock"]],
    ["Dangerously in Love 2","Beyoncé",2003,["international"]],
    ["Music of the Sun","Rihanna",2005,["international"]],
    ["Before the Goodbye","Britney Spears",2001,["international"]],
    ["Piano & I","Alicia Keys",2001,["international"]],
    ["Runaway","Linkin Park",2000,["international","rock"]],
    ["Boys Boys Boys","Lady Gaga",2008,["international"]],
    ["Everything’s Not Lost / Life Is for Living","Coldplay",2000,["international","rock"]],
    ["Jenny Was a Friend of Mine","The Killers",2004,["international","rock"]],
    ["Naughty Girl","Beyoncé",2003,["international"]],
    ["Pon de Replay","Rihanna",2005,["international"]],
    ["Boys","Britney Spears",2001,["international"]],
    ["Rock Wit U","Alicia Keys",2001,["international"]],
    ["Faint","Linkin Park",2003,["international","rock"]],
    ["Brown Eyes","Lady Gaga",2008,["international"]],
    ["Spies","Coldplay",2000,["international","rock"]],
    ["Why Don’t You Find Out for Yourself","The Killers",2005,["international","rock"]],
    ["Speechless","Beyoncé",2003,["international"]],
    ["That La, La, La","Rihanna",2005,["international"]],
    ["The Answer","Britney Spears",2003,["international"]],
    ["Never Felt This Way","Alicia Keys",2002,["international"]],
    ["Figure.09","Linkin Park",2003,["international","rock"]],
    ["Disco Heaven","Lady Gaga",2008,["international"]],
    ["Trouble","Coldplay",2000,["international","rock"]],
    ["Bones","The Killers",2006,["international","rock"]],
    ["Yes","Beyoncé",2003,["international"]],
    ["Coulda Been the One","Rihanna",2006,["international"]],
    ["Do Somethin’","Britney Spears",2004,["international"]],
    ["Someday We'll All Be Free","Alicia Keys",2002,["international"]],
    ["Hit the Floor","Linkin Park",2003,["international","rock"]],
    ["I Like It Rough","Lady Gaga",2008,["international"]],
    ["1.36","Coldplay",2002,["international","rock"]],
    ["Exitlude","The Killers",2006,["international","rock"]],
    ["Everything I Do","Beyoncé",2004,["international"]],
    ["Kisses Don’t Lie","Rihanna",2006,["international"]],
    ["Break the Ice","Britney Spears",2005,["international"]],
    ["Dragon Days","Alicia Keys",2003,["international"]],
    ["Lying From You","Linkin Park",2003,["international","rock"]],
    ["Money Honey","Lady Gaga",2008,["international"]],
    ["Daylight","Coldplay",2002,["international","rock"]],
    ["For Reasons Unknown","The Killers",2006,["international","rock"]],
    ["Creole","Beyoncé",2006,["international"]],
    ["Selfish Girl","Rihanna",2006,["international"]],
    ["Heaven on Earth","Britney Spears",2007,["international"]],
    ["If I Ain’t Got You","Alicia Keys",2003,["international"]],
    ["Bleed It Out","Linkin Park",2007,["international","rock"]],
    ["Paparazzi","Lady Gaga",2008,["international"]],
    ["Green Eyes","Coldplay",2002,["international","rock"]],
    ["If It Hadn’t Been for Love","Adele",2010,["international"]],
    ["Fall","Ed Sheeran",2010,["international"]],
    ["Enchanted","Taylor Swift",2010,["international"]],
    ["Count on Me","Bruno Mars",2010,["international"]],
    ["Be the One","Dua Lipa",2015,["international"]],
    ["Adaptation","The Weeknd",2013,["international"]],
    ["Don’t You Remember","Adele",2011,["international"]],
    ["Fire Alarms","Ed Sheeran",2010,["international"]],
    ["Innocent","Taylor Swift",2010,["international"]],
    ["Grenade","Bruno Mars",2010,["international"]],
    ["Hotter Than Hell","Dua Lipa",2016,["international"]],
    ["Kiss Land","The Weeknd",2013,["international"]],
    ["Hiding My Heart","Adele",2011,["international"]],
    ["Homeless","Ed Sheeran",2010,["international"]],
    ["Ours","Taylor Swift",2010,["international"]],
    ["Somewhere in Brooklyn","Bruno Mars",2010,["international"]],
  ];

  function slugify(value) {
    return value
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  }

  function decadeTag(year) {
    return `${String(year).slice(2, 3)}0s`;
  }

  function spotifySearchUrl(title, artist) {
    return `https://open.spotify.com/search/${encodeURIComponent(`${title} ${artist}`)}`;
  }

  function songCategory(tags) {
    return tags.includes("da") ? "danish" : "international";
  }

  function expandedSong([title, artist, year, tags], extraTags = []) {
    return {
      id: `${slugify(artist)}-${slugify(title)}`,
      title,
      artist,
      year,
      spotifyUri: "",
      spotifyUrl: spotifySearchUrl(title, artist),
      category: songCategory(tags),
      tags: [decadeTag(year), ...tags, ...extraTags],
    };
  }

  const baseSongs = songs.map((song) => ({
    ...song,
    category: "international",
    tags: [...new Set([...(song.tags || []), "international"])],
  }));

  window.SANGQUIZ_SONGS = baseSongs.concat(
    extraSongs.concat(additionalSongs).map((song) => expandedSong(song)),
    originExpansionSongs.map((song) => expandedSong(song, ["origin-expansion"])),
    categoryExpansionSongs.map((song) => expandedSong(song, ["catalog-expansion"])),
  );
})();
