(() => {
  "use strict";

  window.SANGQUIZ_SONGS = [
    {
      id: "abba-dancing-queen",
      title: "Dancing Queen",
      artist: "ABBA",
      year: 1976,
      spotifyUri: "spotify:track:0GjEhVFGZW8afUYGChu3Rr",
      spotifyUrl: "https://open.spotify.com/track/0GjEhVFGZW8afUYGChu3Rr",
      tags: ["70s", "pop", "party"],
    },
    {
      id: "queen-bohemian-rhapsody",
      title: "Bohemian Rhapsody",
      artist: "Queen",
      year: 1975,
      spotifyUri: "spotify:track:7tFiyTwD0nx5a1eklYtX2J",
      spotifyUrl: "https://open.spotify.com/track/7tFiyTwD0nx5a1eklYtX2J",
      tags: ["70s", "rock"],
    },
    {
      id: "michael-jackson-billie-jean",
      title: "Billie Jean",
      artist: "Michael Jackson",
      year: 1982,
      spotifyUri: "spotify:track:5ChkMS8OtdzJeqyybCc9R5",
      spotifyUrl: "https://open.spotify.com/track/5ChkMS8OtdzJeqyybCc9R5",
      tags: ["80s", "pop"],
    },
    {
      id: "toto-africa",
      title: "Africa",
      artist: "TOTO",
      year: 1982,
      spotifyUri: "spotify:track:2374M0fQpWi3dLnB54qaLX",
      spotifyUrl: "https://open.spotify.com/track/2374M0fQpWi3dLnB54qaLX",
      tags: ["80s", "rock", "party"],
    },
    {
      id: "a-ha-take-on-me",
      title: "Take On Me",
      artist: "a-ha",
      year: 1985,
      spotifyUri: "spotify:track:2WfaOiMkCvy7F5fcp2zZ8L",
      spotifyUrl: "https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L",
      tags: ["80s", "pop"],
    },
    {
      id: "whitney-i-wanna-dance",
      title: "I Wanna Dance with Somebody",
      artist: "Whitney Houston",
      year: 1987,
      spotifyUri: "spotify:track:2tUBqZG2AbRi7Q0BIrVrEj",
      spotifyUrl: "https://open.spotify.com/track/2tUBqZG2AbRi7Q0BIrVrEj",
      tags: ["80s", "pop", "party"],
    },
    {
      id: "nirvana-smells-like-teen-spirit",
      title: "Smells Like Teen Spirit",
      artist: "Nirvana",
      year: 1991,
      spotifyUri: "spotify:track:5ghIJDpPoe3CfHMGu71E6T",
      spotifyUrl: "https://open.spotify.com/track/5ghIJDpPoe3CfHMGu71E6T",
      tags: ["90s", "rock"],
    },
    {
      id: "oasis-wonderwall",
      title: "Wonderwall",
      artist: "Oasis",
      year: 1995,
      spotifyUri: "spotify:track:5qqabIl2vWzo9ApSC317sa",
      spotifyUrl: "https://open.spotify.com/track/5qqabIl2vWzo9ApSC317sa",
      tags: ["90s", "rock"],
    },
    {
      id: "backstreet-boys-i-want-it-that-way",
      title: "I Want It That Way",
      artist: "Backstreet Boys",
      year: 1999,
      spotifyUri: "spotify:track:6e40mgJiCid5HRAGrbpGA6",
      spotifyUrl: "https://open.spotify.com/track/6e40mgJiCid5HRAGrbpGA6",
      tags: ["90s", "pop", "party"],
    },
    {
      id: "britney-spears-toxic",
      title: "Toxic",
      artist: "Britney Spears",
      year: 2003,
      spotifyUri: "spotify:track:6I9VzXrHxO9rA9A5euc8Ak",
      spotifyUrl: "https://open.spotify.com/track/6I9VzXrHxO9rA9A5euc8Ak",
      tags: ["00s", "pop"],
    },
    {
      id: "outkast-hey-ya",
      title: "Hey Ya!",
      artist: "Outkast",
      year: 2003,
      spotifyUri: "spotify:track:2PpruBYCo4H7WOBJ7Q2EwM",
      spotifyUrl: "https://open.spotify.com/track/2PpruBYCo4H7WOBJ7Q2EwM",
      tags: ["00s", "party"],
    },
    {
      id: "the-killers-mr-brightside",
      title: "Mr. Brightside",
      artist: "The Killers",
      year: 2003,
      spotifyUri: "spotify:track:003vvx7Niy0yvhvHt4a68B",
      spotifyUrl: "https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B",
      tags: ["00s", "rock", "party"],
    },
    {
      id: "shakira-hips-dont-lie",
      title: "Hips Don't Lie",
      artist: "Shakira",
      year: 2005,
      spotifyUri: "spotify:track:3ZFTkvIE7kyPt6Nu3PEa7V",
      spotifyUrl: "https://open.spotify.com/track/3ZFTkvIE7kyPt6Nu3PEa7V",
      tags: ["00s", "pop", "party"],
    },
    {
      id: "gnarls-barkley-crazy",
      title: "Crazy",
      artist: "Gnarls Barkley",
      year: 2006,
      spotifyUri: "spotify:track:1vxw6aYJls2oq3gW0DujAo",
      spotifyUrl: "https://open.spotify.com/track/1vxw6aYJls2oq3gW0DujAo",
      tags: ["00s", "soul", "pop"],
    },
    {
      id: "beyonce-single-ladies",
      title: "Single Ladies",
      artist: "Beyonce",
      year: 2008,
      spotifyUri: "spotify:track:5R9a4t5t5O0IsznsrKPVro",
      spotifyUrl: "https://open.spotify.com/track/5R9a4t5t5O0IsznsrKPVro",
      tags: ["00s", "pop", "party"],
    },
    {
      id: "lady-gaga-bad-romance",
      title: "Bad Romance",
      artist: "Lady Gaga",
      year: 2009,
      spotifyUri: "spotify:track:0SiywuOBRcynK0uKGWdCnn",
      spotifyUrl: "https://open.spotify.com/track/0SiywuOBRcynK0uKGWdCnn",
      tags: ["00s", "pop"],
    },
    {
      id: "adele-rolling-in-the-deep",
      title: "Rolling in the Deep",
      artist: "Adele",
      year: 2010,
      spotifyUri: "spotify:track:1c8gk2PeTE04A1pIDH9YMk",
      spotifyUrl: "https://open.spotify.com/track/1c8gk2PeTE04A1pIDH9YMk",
      tags: ["10s", "pop"],
    },
    {
      id: "daft-punk-get-lucky",
      title: "Get Lucky",
      artist: "Daft Punk feat. Pharrell Williams",
      year: 2013,
      spotifyUri: "spotify:track:2Foc5Q5nqNiosCNqttzHof",
      spotifyUrl: "https://open.spotify.com/track/2Foc5Q5nqNiosCNqttzHof",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "avicii-wake-me-up",
      title: "Wake Me Up",
      artist: "Avicii",
      year: 2013,
      spotifyUri: "spotify:track:0nrRP2bk19rLc0orkWPQk2",
      spotifyUrl: "https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "pharrell-happy",
      title: "Happy",
      artist: "Pharrell Williams",
      year: 2013,
      spotifyUri: "spotify:track:60nZcImufyMA1MKQY3dcCH",
      spotifyUrl: "https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "mark-ronson-uptown-funk",
      title: "Uptown Funk",
      artist: "Mark Ronson feat. Bruno Mars",
      year: 2014,
      spotifyUri: "spotify:track:32OlwWuMpZ6b0aN2RZOeMS",
      spotifyUrl: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS",
      tags: ["10s", "funk", "party"],
    },
    {
      id: "taylor-swift-shake-it-off",
      title: "Shake It Off",
      artist: "Taylor Swift",
      year: 2014,
      spotifyUri: "spotify:track:0cqRj7pUJDkTCEsJkx8snD",
      spotifyUrl: "https://open.spotify.com/track/0cqRj7pUJDkTCEsJkx8snD",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "justin-bieber-sorry",
      title: "Sorry",
      artist: "Justin Bieber",
      year: 2015,
      spotifyUri: "spotify:track:09CtPGIpYB4BrO8qb1RGsF",
      spotifyUrl: "https://open.spotify.com/track/09CtPGIpYB4BrO8qb1RGsF",
      tags: ["10s", "pop"],
    },
    {
      id: "ed-sheeran-shape-of-you",
      title: "Shape of You",
      artist: "Ed Sheeran",
      year: 2017,
      spotifyUri: "spotify:track:7qiZfU4dY1lWllzX7mPBI3",
      spotifyUrl: "https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3",
      tags: ["10s", "pop"],
    },
    {
      id: "billie-eilish-bad-guy",
      title: "bad guy",
      artist: "Billie Eilish",
      year: 2019,
      spotifyUri: "spotify:track:2Fxmhks0bxGSBdJ92vM42m",
      spotifyUrl: "https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m",
      tags: ["10s", "pop"],
    },
    {
      id: "the-weeknd-blinding-lights",
      title: "Blinding Lights",
      artist: "The Weeknd",
      year: 2019,
      spotifyUri: "spotify:track:0VjIjW4GlUZAMYd2vXMi3b",
      spotifyUrl: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "dua-lipa-dont-start-now",
      title: "Don't Start Now",
      artist: "Dua Lipa",
      year: 2019,
      spotifyUri: "spotify:track:6WrI0LAC5M1Rw2MnX2ZvEg",
      spotifyUrl: "https://open.spotify.com/track/6WrI0LAC5M1Rw2MnX2ZvEg",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "the-weeknd-save-your-tears",
      title: "Save Your Tears",
      artist: "The Weeknd",
      year: 2020,
      spotifyUri: "spotify:track:5QO79kh1waicV47BqGRL3g",
      spotifyUrl: "https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g",
      tags: ["20s", "pop"],
    },
    {
      id: "harry-styles-as-it-was",
      title: "As It Was",
      artist: "Harry Styles",
      year: 2022,
      spotifyUri: "spotify:track:4LRPiXqCikLlN15c3yImP7",
      spotifyUrl: "https://open.spotify.com/track/4LRPiXqCikLlN15c3yImP7",
      tags: ["20s", "pop"],
    },
    {
      id: "miley-cyrus-flowers",
      title: "Flowers",
      artist: "Miley Cyrus",
      year: 2023,
      spotifyUri: "spotify:track:0yLdNVWF3Srea0uzk55zFn",
      spotifyUrl: "https://open.spotify.com/track/0yLdNVWF3Srea0uzk55zFn",
      tags: ["20s", "pop"],
    },
  ];
})();
