(() => {
  "use strict";

  const songs = [
    {
      id: "abba-dancing-queen",
      title: "Dancing Queen",
      artist: "ABBA",
      year: 1976,
      spotifyUri: "spotify:track:0GjEhVFGZW8afUYGChu3Rr",
      spotifyUrl: "https://open.spotify.com/track/0GjEhVFGZW8afUYGChu3Rr",
      tags: ["70s", "pop", "party"],
    },
    {
      id: "queen-bohemian-rhapsody",
      title: "Bohemian Rhapsody",
      artist: "Queen",
      year: 1975,
      spotifyUri: "spotify:track:7tFiyTwD0nx5a1eklYtX2J",
      spotifyUrl: "https://open.spotify.com/track/7tFiyTwD0nx5a1eklYtX2J",
      tags: ["70s", "rock"],
    },
    {
      id: "michael-jackson-billie-jean",
      title: "Billie Jean",
      artist: "Michael Jackson",
      year: 1982,
      spotifyUri: "spotify:track:5ChkMS8OtdzJeqyybCc9R5",
      spotifyUrl: "https://open.spotify.com/track/5ChkMS8OtdzJeqyybCc9R5",
      tags: ["80s", "pop"],
    },
    {
      id: "toto-africa",
      title: "Africa",
      artist: "TOTO",
      year: 1982,
      spotifyUri: "spotify:track:2374M0fQpWi3dLnB54qaLX",
      spotifyUrl: "https://open.spotify.com/track/2374M0fQpWi3dLnB54qaLX",
      tags: ["80s", "rock", "party"],
    },
    {
      id: "a-ha-take-on-me",
      title: "Take On Me",
      artist: "a-ha",
      year: 1985,
      spotifyUri: "spotify:track:2WfaOiMkCvy7F5fcp2zZ8L",
      spotifyUrl: "https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L",
      tags: ["80s", "pop"],
    },
    {
      id: "whitney-i-wanna-dance",
      title: "I Wanna Dance with Somebody",
      artist: "Whitney Houston",
      year: 1987,
      spotifyUri: "spotify:track:2tUBqZG2AbRi7Q0BIrVrEj",
      spotifyUrl: "https://open.spotify.com/track/2tUBqZG2AbRi7Q0BIrVrEj",
      tags: ["80s", "pop", "party"],
    },
    {
      id: "nirvana-smells-like-teen-spirit",
      title: "Smells Like Teen Spirit",
      artist: "Nirvana",
      year: 1991,
      spotifyUri: "spotify:track:5ghIJDpPoe3CfHMGu71E6T",
      spotifyUrl: "https://open.spotify.com/track/5ghIJDpPoe3CfHMGu71E6T",
      tags: ["90s", "rock"],
    },
    {
      id: "oasis-wonderwall",
      title: "Wonderwall",
      artist: "Oasis",
      year: 1995,
      spotifyUri: "spotify:track:5qqabIl2vWzo9ApSC317sa",
      spotifyUrl: "https://open.spotify.com/track/5qqabIl2vWzo9ApSC317sa",
      tags: ["90s", "rock"],
    },
    {
      id: "backstreet-boys-i-want-it-that-way",
      title: "I Want It That Way",
      artist: "Backstreet Boys",
      year: 1999,
      spotifyUri: "spotify:track:6e40mgJiCid5HRAGrbpGA6",
      spotifyUrl: "https://open.spotify.com/track/6e40mgJiCid5HRAGrbpGA6",
      tags: ["90s", "pop", "party"],
    },
    {
      id: "britney-spears-toxic",
      title: "Toxic",
      artist: "Britney Spears",
      year: 2003,
      spotifyUri: "spotify:track:6I9VzXrHxO9rA9A5euc8Ak",
      spotifyUrl: "https://open.spotify.com/track/6I9VzXrHxO9rA9A5euc8Ak",
      tags: ["00s", "pop"],
    },
    {
      id: "outkast-hey-ya",
      title: "Hey Ya!",
      artist: "Outkast",
      year: 2003,
      spotifyUri: "spotify:track:2PpruBYCo4H7WOBJ7Q2EwM",
      spotifyUrl: "https://open.spotify.com/track/2PpruBYCo4H7WOBJ7Q2EwM",
      tags: ["00s", "party"],
    },
    {
      id: "the-killers-mr-brightside",
      title: "Mr. Brightside",
      artist: "The Killers",
      year: 2003,
      spotifyUri: "spotify:track:003vvx7Niy0yvhvHt4a68B",
      spotifyUrl: "https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B",
      tags: ["00s", "rock", "party"],
    },
    {
      id: "shakira-hips-dont-lie",
      title: "Hips Don't Lie",
      artist: "Shakira",
      year: 2005,
      spotifyUri: "spotify:track:3ZFTkvIE7kyPt6Nu3PEa7V",
      spotifyUrl: "https://open.spotify.com/track/3ZFTkvIE7kyPt6Nu3PEa7V",
      tags: ["00s", "pop", "party"],
    },
    {
      id: "gnarls-barkley-crazy",
      title: "Crazy",
      artist: "Gnarls Barkley",
      year: 2006,
      spotifyUri: "spotify:track:1vxw6aYJls2oq3gW0DujAo",
      spotifyUrl: "https://open.spotify.com/track/1vxw6aYJls2oq3gW0DujAo",
      tags: ["00s", "soul", "pop"],
    },
    {
      id: "beyonce-single-ladies",
      title: "Single Ladies",
      artist: "Beyonce",
      year: 2008,
      spotifyUri: "spotify:track:5R9a4t5t5O0IsznsrKPVro",
      spotifyUrl: "https://open.spotify.com/track/5R9a4t5t5O0IsznsrKPVro",
      tags: ["00s", "pop", "party"],
    },
    {
      id: "lady-gaga-bad-romance",
      title: "Bad Romance",
      artist: "Lady Gaga",
      year: 2009,
      spotifyUri: "spotify:track:0SiywuOBRcynK0uKGWdCnn",
      spotifyUrl: "https://open.spotify.com/track/0SiywuOBRcynK0uKGWdCnn",
      tags: ["00s", "pop"],
    },
    {
      id: "adele-rolling-in-the-deep",
      title: "Rolling in the Deep",
      artist: "Adele",
      year: 2010,
      spotifyUri: "spotify:track:1c8gk2PeTE04A1pIDH9YMk",
      spotifyUrl: "https://open.spotify.com/track/1c8gk2PeTE04A1pIDH9YMk",
      tags: ["10s", "pop"],
    },
    {
      id: "daft-punk-get-lucky",
      title: "Get Lucky",
      artist: "Daft Punk feat. Pharrell Williams",
      year: 2013,
      spotifyUri: "spotify:track:2Foc5Q5nqNiosCNqttzHof",
      spotifyUrl: "https://open.spotify.com/track/2Foc5Q5nqNiosCNqttzHof",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "avicii-wake-me-up",
      title: "Wake Me Up",
      artist: "Avicii",
      year: 2013,
      spotifyUri: "spotify:track:0nrRP2bk19rLc0orkWPQk2",
      spotifyUrl: "https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "pharrell-happy",
      title: "Happy",
      artist: "Pharrell Williams",
      year: 2013,
      spotifyUri: "spotify:track:60nZcImufyMA1MKQY3dcCH",
      spotifyUrl: "https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "mark-ronson-uptown-funk",
      title: "Uptown Funk",
      artist: "Mark Ronson feat. Bruno Mars",
      year: 2014,
      spotifyUri: "spotify:track:32OlwWuMpZ6b0aN2RZOeMS",
      spotifyUrl: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS",
      tags: ["10s", "funk", "party"],
    },
    {
      id: "taylor-swift-shake-it-off",
      title: "Shake It Off",
      artist: "Taylor Swift",
      year: 2014,
      spotifyUri: "spotify:track:0cqRj7pUJDkTCEsJkx8snD",
      spotifyUrl: "https://open.spotify.com/track/0cqRj7pUJDkTCEsJkx8snD",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "justin-bieber-sorry",
      title: "Sorry",
      artist: "Justin Bieber",
      year: 2015,
      spotifyUri: "spotify:track:09CtPGIpYB4BrO8qb1RGsF",
      spotifyUrl: "https://open.spotify.com/track/09CtPGIpYB4BrO8qb1RGsF",
      tags: ["10s", "pop"],
    },
    {
      id: "ed-sheeran-shape-of-you",
      title: "Shape of You",
      artist: "Ed Sheeran",
      year: 2017,
      spotifyUri: "spotify:track:7qiZfU4dY1lWllzX7mPBI3",
      spotifyUrl: "https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3",
      tags: ["10s", "pop"],
    },
    {
      id: "billie-eilish-bad-guy",
      title: "bad guy",
      artist: "Billie Eilish",
      year: 2019,
      spotifyUri: "spotify:track:2Fxmhks0bxGSBdJ92vM42m",
      spotifyUrl: "https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m",
      tags: ["10s", "pop"],
    },
    {
      id: "the-weeknd-blinding-lights",
      title: "Blinding Lights",
      artist: "The Weeknd",
      year: 2019,
      spotifyUri: "spotify:track:0VjIjW4GlUZAMYd2vXMi3b",
      spotifyUrl: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b",
      tags: ["10s", "pop", "party"],
    },
    {
      id: "dua-lipa-dont-start-now",
      title: "Don't Start Now",
      artist: "Dua Lipa",
      year: 2019,
      spotifyUri: "spotify:track:6WrI0LAC5M1Rw2MnX2ZvEg",
      spotifyUrl: "https://open.spotify.com/track/6WrI0LAC5M1Rw2MnX2ZvEg",
      tags: ["10s", "dance", "party"],
    },
    {
      id: "the-weeknd-save-your-tears",
      title: "Save Your Tears",
      artist: "The Weeknd",
      year: 2020,
      spotifyUri: "spotify:track:5QO79kh1waicV47BqGRL3g",
      spotifyUrl: "https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g",
      tags: ["20s", "pop"],
    },
    {
      id: "harry-styles-as-it-was",
      title: "As It Was",
      artist: "Harry Styles",
      year: 2022,
      spotifyUri: "spotify:track:4LRPiXqCikLlN15c3yImP7",
      spotifyUrl: "https://open.spotify.com/track/4LRPiXqCikLlN15c3yImP7",
      tags: ["20s", "pop"],
    },
    {
      id: "miley-cyrus-flowers",
      title: "Flowers",
      artist: "Miley Cyrus",
      year: 2023,
      spotifyUri: "spotify:track:0yLdNVWF3Srea0uzk55zFn",
      spotifyUrl: "https://open.spotify.com/track/0yLdNVWF3Srea0uzk55zFn",
      tags: ["20s", "pop"],
    },
  ];

  const extraSongs = [
    ["Kvinde Min", "Gasolin'", 1975, ["da", "rock"]],
    ["Rabalderstræde", "Gasolin'", 1975, ["da", "rock"]],
    ["Langebro", "Gasolin'", 1971, ["da", "rock"]],
    ["Hva' Gør Vi Nu, Lille Du?", "Gasolin'", 1976, ["da", "rock"]],
    ["Midt Om Natten", "Kim Larsen", 1983, ["da", "party"]],
    ["Papirsklip", "Kim Larsen", 1983, ["da", "pop"]],
    ["This Is My Life", "Kim Larsen", 1983, ["da", "pop"]],
    ["Jutlandia", "Kim Larsen & Bellami", 1986, ["da", "rock"]],
    ["Joanna", "Kim Larsen", 1973, ["da", "pop"]],
    ["Hvalen Hvalborg", "Shu-bi-dua", 1976, ["da", "party"]],
    ["Fed Rock", "Shu-bi-dua", 1978, ["da", "rock"]],
    ["Danmark", "Shu-bi-dua", 1978, ["da", "pop"]],
    ["Vuffeli-vov", "Shu-bi-dua", 1980, ["da", "party"]],
    ["De Første Kærester På Månen", "TV-2", 1988, ["da", "pop"]],
    ["Popmusikerens Vise", "TV-2", 1985, ["da", "pop"]],
    ["Kom Lad Os Brokke Os", "TV-2", 1981, ["da", "rock"]],
    ["Alt Hvad Hun Ville Var At Danse", "TV-2", 1988, ["da", "party"]],
    ["Bag Duggede Ruder", "Gnags", 1984, ["da", "rock"]],
    ["Vilde Kaniner", "Gnags", 1984, ["da", "party"]],
    ["Mr. Swing King", "Gnags", 1989, ["da", "party"]],
    ["Når Jeg Bliver Gammel", "Gnags", 1989, ["da", "pop"]],
    ["Vågner I Natten", "Dodo & The Dodos", 1987, ["da", "pop"]],
    ["Sømand Af Verden", "Dodo & The Dodos", 1986, ["da", "pop"]],
    ["Lev Livet Nu", "Dodo & The Dodos", 1989, ["da", "party"]],
    ["Elsk Mig I Nat", "Rocazino", 1985, ["da", "party"]],
    ["All My Love", "Rocazino", 1982, ["da", "pop"]],
    ["Kom Tilbage Nu", "Danseorkestret", 1985, ["da", "party"]],
    ["Regndans", "Danseorkestret", 1986, ["da", "pop"]],
    ["Det Er Mig Der Står Herude Og Banker På", "Thomas Helmig", 1988, ["da", "pop"]],
    ["Stupid Man", "Thomas Helmig", 1994, ["da", "pop"]],
    ["Malaga", "Thomas Helmig", 1986, ["da", "pop"]],
    ["Midnat I Europa", "Thomas Helmig", 1989, ["da", "pop"]],
    ["Tæt På Ækvator", "Lis Sørensen", 1988, ["da", "pop"]],
    ["Mine Øjne De Skal Se", "Lis Sørensen", 1989, ["da", "pop"]],
    ["Fuld Af Nattens Stjerner", "Lis Sørensen", 1993, ["da", "pop"]],
    ["Tusind Stykker", "Anne Linnet", 1988, ["da", "pop"]],
    ["Barndommens Gade", "Anne Linnet", 1986, ["da", "pop"]],
    ["Smuk Og Dejlig", "Shit & Chanel", 1975, ["da", "pop"]],
    ["Den Jeg Elsker", "Sanne Salomonsen", 1988, ["da", "pop"]],
    ["Kærligheden Kalder", "Sanne Salomonsen", 1989, ["da", "pop"]],
    ["Elsker Dig For Evigt", "Lars H.U.G.", 1987, ["da", "pop"]],
    ["Copenhagen Dreaming", "Love Shop", 1997, ["da", "rock"]],
    ["Movie Klip", "Nephew", 2004, ["da", "rock"]],
    ["Igen & Igen &", "Nephew", 2006, ["da", "rock"]],
    ["Hospital", "Nephew", 2004, ["da", "rock"]],
    ["Lækker", "Nik & Jay", 2003, ["da", "party"]],
    ["Hot!", "Nik & Jay", 2002, ["da", "party"]],
    ["Boing!", "Nik & Jay", 2004, ["da", "party"]],
    ["Mod Solnedgangen", "Nik & Jay", 2011, ["da", "pop"]],
    ["Engel", "Rasmus Seebach", 2009, ["da", "pop"]],
    ["Natteravn", "Rasmus Seebach", 2010, ["da", "pop"]],
    ["Olivia", "Rasmus Seebach", 2010, ["da", "pop"]],
    ["Millionær", "Rasmus Seebach feat. Ankerstjerne", 2010, ["da", "pop"]],
    ["Kun For Mig", "Medina", 2008, ["da", "dance"]],
    ["Vi To", "Medina", 2009, ["da", "pop"]],
    ["For Altid", "Medina", 2011, ["da", "dance"]],
    ["Fascination", "Alphabeat", 2007, ["da", "party"]],
    ["10.000 Nights", "Alphabeat", 2007, ["da", "party"]],
    ["From Paris To Berlin", "Infernal", 2004, ["da", "dance"]],
    ["Barbie Girl", "Aqua", 1997, ["da", "party"]],
    ["Imagine", "John Lennon", 1971, ["international", "pop"]],
    ["Stayin' Alive", "Bee Gees", 1977, ["international", "party"]],
    ["September", "Earth, Wind & Fire", 1978, ["international", "party"]],
    ["Hotel California", "Eagles", 1976, ["international", "rock"]],
    ["Don't Stop Me Now", "Queen", 1978, ["international", "rock"]],
    ["Another One Bites The Dust", "Queen", 1980, ["international", "rock"]],
    ["Superstition", "Stevie Wonder", 1972, ["international", "funk"]],
    ["Sweet Home Alabama", "Lynyrd Skynyrd", 1974, ["international", "rock"]],
    ["Go Your Own Way", "Fleetwood Mac", 1977, ["international", "rock"]],
    ["Dreams", "Fleetwood Mac", 1977, ["international", "rock"]],
    ["Born To Run", "Bruce Springsteen", 1975, ["international", "rock"]],
    ["Dancing In The Dark", "Bruce Springsteen", 1984, ["international", "rock"]],
    ["Livin' On A Prayer", "Bon Jovi", 1986, ["international", "rock", "party"]],
    ["Sweet Child O' Mine", "Guns N' Roses", 1987, ["international", "rock"]],
    ["Every Breath You Take", "The Police", 1983, ["international", "pop"]],
    ["Don't You (Forget About Me)", "Simple Minds", 1985, ["international", "pop"]],
    ["Girls Just Want To Have Fun", "Cyndi Lauper", 1983, ["international", "party"]],
    ["Like A Virgin", "Madonna", 1984, ["international", "pop"]],
    ["Like A Prayer", "Madonna", 1989, ["international", "pop"]],
    ["Purple Rain", "Prince", 1984, ["international", "pop"]],
    ["When Doves Cry", "Prince", 1984, ["international", "pop"]],
    ["Never Gonna Give You Up", "Rick Astley", 1987, ["international", "party"]],
    ["Faith", "George Michael", 1987, ["international", "pop"]],
    ["Careless Whisper", "George Michael", 1984, ["international", "pop"]],
    ["Wake Me Up Before You Go-Go", "Wham!", 1984, ["international", "party"]],
    ["Sweet Dreams", "Eurythmics", 1983, ["international", "pop"]],
    ["Here I Go Again", "Whitesnake", 1987, ["international", "rock"]],
    ["The Final Countdown", "Europe", 1986, ["international", "rock"]],
    ["Eye Of The Tiger", "Survivor", 1982, ["international", "rock"]],
    ["Total Eclipse Of The Heart", "Bonnie Tyler", 1983, ["international", "pop"]],
    ["Losing My Religion", "R.E.M.", 1991, ["international", "rock"]],
    ["Zombie", "The Cranberries", 1994, ["international", "rock"]],
    ["Creep", "Radiohead", 1992, ["international", "rock"]],
    ["No Rain", "Blind Melon", 1992, ["international", "rock"]],
    ["Basket Case", "Green Day", 1994, ["international", "rock"]],
    ["Song 2", "Blur", 1997, ["international", "rock"]],
    ["Bitter Sweet Symphony", "The Verve", 1997, ["international", "rock"]],
    ["Torn", "Natalie Imbruglia", 1997, ["international", "pop"]],
    ["...Baby One More Time", "Britney Spears", 1998, ["international", "pop"]],
    ["Wannabe", "Spice Girls", 1996, ["international", "party"]],
    ["Mambo No. 5", "Lou Bega", 1999, ["international", "party"]],
    ["Smooth", "Santana feat. Rob Thomas", 1999, ["international", "pop"]],
    ["Believe", "Cher", 1998, ["international", "dance"]],
    ["All Star", "Smash Mouth", 1999, ["international", "party"]],
    ["Blue (Da Ba Dee)", "Eiffel 65", 1998, ["international", "dance"]],
    ["Around The World", "Daft Punk", 1997, ["international", "dance"]],
    ["One More Time", "Daft Punk", 2000, ["international", "dance"]],
    ["Seven Nation Army", "The White Stripes", 2003, ["international", "rock"]],
    ["In The End", "Linkin Park", 2000, ["international", "rock"]],
    ["Numb", "Linkin Park", 2003, ["international", "rock"]],
    ["Complicated", "Avril Lavigne", 2002, ["international", "pop"]],
    ["Sk8er Boi", "Avril Lavigne", 2002, ["international", "rock"]],
    ["Crazy In Love", "Beyoncé feat. Jay-Z", 2003, ["international", "party"]],
    ["Umbrella", "Rihanna feat. Jay-Z", 2007, ["international", "pop"]],
    ["Don't Stop The Music", "Rihanna", 2007, ["international", "dance"]],
    ["Poker Face", "Lady Gaga", 2008, ["international", "pop"]],
    ["Just Dance", "Lady Gaga", 2008, ["international", "dance"]],
    ["I Gotta Feeling", "The Black Eyed Peas", 2009, ["international", "party"]],
    ["Where Is The Love?", "The Black Eyed Peas", 2003, ["international", "pop"]],
    ["Feel Good Inc.", "Gorillaz", 2005, ["international", "pop"]],
    ["Firework", "Katy Perry", 2010, ["international", "pop"]],
    ["Teenage Dream", "Katy Perry", 2010, ["international", "pop"]],
    ["Call Me Maybe", "Carly Rae Jepsen", 2011, ["international", "party"]],
    ["Somebody That I Used To Know", "Gotye feat. Kimbra", 2011, ["international", "pop"]],
    ["We Found Love", "Rihanna feat. Calvin Harris", 2011, ["international", "dance"]],
    ["Can't Hold Us", "Macklemore & Ryan Lewis", 2011, ["international", "party"]],
    ["Thrift Shop", "Macklemore & Ryan Lewis", 2012, ["international", "party"]],
    ["Radioactive", "Imagine Dragons", 2012, ["international", "rock"]],
    ["Demons", "Imagine Dragons", 2012, ["international", "pop"]],
    ["Royals", "Lorde", 2013, ["international", "pop"]],
    ["Chandelier", "Sia", 2014, ["international", "pop"]],
    ["Cheap Thrills", "Sia", 2016, ["international", "party"]],
    ["Hello", "Adele", 2015, ["international", "pop"]],
    ["Someone Like You", "Adele", 2011, ["international", "pop"]],
    ["Can't Stop The Feeling!", "Justin Timberlake", 2016, ["international", "party"]],
    ["Despacito", "Luis Fonsi feat. Daddy Yankee", 2017, ["international", "party"]],
    ["Havana", "Camila Cabello feat. Young Thug", 2017, ["international", "pop"]],
    ["Señorita", "Shawn Mendes & Camila Cabello", 2019, ["international", "pop"]],
    ["Old Town Road", "Lil Nas X", 2018, ["international", "party"]],
    ["Dance Monkey", "Tones And I", 2019, ["international", "pop"]],
    ["Watermelon Sugar", "Harry Styles", 2019, ["international", "pop"]],
    ["Levitating", "Dua Lipa", 2020, ["international", "dance"]],
    ["Physical", "Dua Lipa", 2020, ["international", "dance"]],
    ["Bad Habits", "Ed Sheeran", 2021, ["international", "pop"]],
    ["Shivers", "Ed Sheeran", 2021, ["international", "pop"]],
    ["Drivers License", "Olivia Rodrigo", 2021, ["international", "pop"]],
    ["Good 4 U", "Olivia Rodrigo", 2021, ["international", "rock"]],
    ["Heat Waves", "Glass Animals", 2020, ["international", "pop"]],
    ["Anti-Hero", "Taylor Swift", 2022, ["international", "pop"]],
    ["Espresso", "Sabrina Carpenter", 2024, ["international", "pop"]],
  ];

  function slugify(value) {
    return value
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  }

  function decadeTag(year) {
    return `${String(year).slice(2, 3)}0s`;
  }

  function spotifySearchUrl(title, artist) {
    return `https://open.spotify.com/search/${encodeURIComponent(`${title} ${artist}`)}`;
  }

  window.SANGQUIZ_SONGS = songs.concat(
    extraSongs.map(([title, artist, year, tags]) => ({
      id: `${slugify(artist)}-${slugify(title)}`,
      title,
      artist,
      year,
      spotifyUri: "",
      spotifyUrl: spotifySearchUrl(title, artist),
      tags: [decadeTag(year), ...tags],
    })),
  );
})();
